import type { AgentSendPayload } from '@shared/types/agent';
import type { SessionId } from '@shared/types/brand';
import type { SessionDetail } from '@shared/types/session';
import type { SkillDiscoveryItem } from '@shared/types/standards';
import type { WaggleCollaborationStatus, WaggleConfig } from '@shared/types/waggle';
import type { AgentChatStatus, AgentCompactionStatus } from '@/features/chat/hooks/useAgentChat';
import type { useStreamingPhase } from '@/features/chat/hooks/useStreamingPhase';
import type { SessionForkTarget } from '../lib/session-fork-targets';
import type { ChatComposerSectionState } from '../model';
export interface ComposerSectionParams {
    readonly isLoading: boolean;
    readonly isSteering: boolean;
    readonly status: AgentChatStatus;
    readonly compactionStatus: AgentCompactionStatus | null;
    readonly activeSessionId: SessionId | null;
    readonly session: SessionDetail | null;
    readonly isFirstMessage: boolean;
    readonly waggleStatus: WaggleCollaborationStatus;
    readonly commandPaletteOpen: boolean;
    readonly slashSkills: readonly SkillDiscoveryItem[];
    readonly forkSelectorOpen: boolean;
    readonly forkTargets: readonly SessionForkTarget[];
    readonly phase: ReturnType<typeof useStreamingPhase>;
    readonly stop: () => void;
    readonly showToast: (message: string) => void;
    readonly handleSteer: (messageId: string) => Promise<void>;
    readonly handleSendWithWaggle: (payload: AgentSendPayload) => Promise<void>;
    readonly handleStartWaggle: (config: WaggleConfig) => void;
    readonly handleStopCollaboration: () => void;
    readonly handleSkipBranchSummary: () => void;
    readonly handleSummarizeBranch: () => void;
    readonly handleStartCustomBranchSummary: () => void;
    readonly handleCancelBranchSummary: () => void;
    readonly handleOpenForkSelector: () => void;
    readonly handleCloseForkSelector: () => void;
    readonly handleSelectForkTarget: (target: SessionForkTarget) => void;
    readonly handleCloneToNewSession: () => void;
}
export declare function useComposerSection(params: ComposerSectionParams): ChatComposerSectionState;
