import type { SessionId } from '@shared/types/brand';
import type { UIMessage } from '@shared/types/chat-ui';
import type { SupportedModelId } from '@shared/types/llm';
import type { SessionInterruptedRun } from '@shared/types/session';
import type { WaggleMessageMetadata } from '@shared/types/waggle';
import type { useStreamingPhase } from '@/features/chat/hooks/useStreamingPhase';
import type { ChatRow } from '../lib/types-chat-row';
import { buildChatRows } from './useBuildChatRows';
export declare function useChatRows(inputs: {
    messages: UIMessage[];
    customMessages?: Parameters<typeof buildChatRows>[0]['customMessages'];
    interactionEvents?: Parameters<typeof buildChatRows>[0]['interactionEvents'];
    isLoading: boolean;
    error: Error | undefined;
    lastUserMessage: string | null;
    dismissedError: string | null;
    sessionId: SessionId | null;
    model: SupportedModelId;
    waggleMetadataLookup: Readonly<Record<string, WaggleMessageMetadata>>;
    phase: ReturnType<typeof useStreamingPhase>;
    interruptedRun?: SessionInterruptedRun;
}): ChatRow[];
