import type { SessionBranchId, SessionId } from '@shared/types/brand';
import type { UIMessage } from '@shared/types/chat-ui';
import type { ExtensionContributionRegistryView } from '@shared/types/extensions';
import type { SupportedModelId } from '@shared/types/llm';
import type { SessionDetail } from '@shared/types/session';
import type { AgentTransportCustomEvent } from '@shared/types/stream';
import type { WaggleCollaborationStatus } from '@shared/types/waggle';
import type { useStreamingPhase } from '@/features/chat/hooks/useStreamingPhase';
import type { AgentInteractionEvent } from '../lib/types-chat-row';
import type { ChatTranscriptSectionState } from '../model';
export interface TranscriptSectionParams {
    readonly messages: UIMessage[];
    readonly customMessages: readonly AgentTransportCustomEvent[];
    readonly interactionEvents: readonly AgentInteractionEvent[];
    readonly isLoading: boolean;
    readonly isSteering: boolean;
    readonly error: Error | undefined;
    readonly streamSignalVersion: number;
    readonly projectPath: string | null;
    readonly recentProjects: readonly string[];
    readonly activeSessionId: SessionId | null;
    readonly activeSession: SessionDetail | null;
    readonly model: SupportedModelId;
    readonly waggleStatus: WaggleCollaborationStatus;
    readonly phase: ReturnType<typeof useStreamingPhase>;
    readonly extensionRegistry: ExtensionContributionRegistryView | null;
    readonly extensionProjectPaths: readonly string[];
    readonly handleOpenProject: () => Promise<void>;
    readonly handleSelectProjectPath: (path: string) => void;
    readonly handleSendText: (content: string) => Promise<void>;
    readonly openSettings: () => void;
    readonly handleDismissInterruptedRun: (runId: string, branchId: SessionBranchId) => void;
    readonly handleBranchFromMessage: (messageId: string) => void;
    readonly handleForkFromMessage: (messageId: string) => void;
    readonly handleViewTurnDiff: (messageId: string) => void;
    readonly turnAnchorMessageIds: ReadonlySet<string>;
    readonly userDidSend: boolean;
    readonly onUserDidSendConsumed: () => void;
}
export declare function useTranscriptSection(params: TranscriptSectionParams): ChatTranscriptSectionState;
