import type { WagglePresetId } from '@shared/types/brand';
import type { WagglePreset } from '@shared/types/waggle';
import { api } from '@/shared/lib/ipc';
import { queryKeys } from './query-keys';
import type { OpenWaggleQueryOptions } from './query-options';
type WagglePresets = Awaited<ReturnType<typeof api.listWagglePresets>>;
export declare function wagglePresetsQueryOptions(projectPath: string | null): OpenWaggleQueryOptions<WagglePresets, Error, WagglePresets, ReturnType<typeof queryKeys.wagglePresets>>;
export declare function useSaveWagglePresetMutation(projectPath: string | null): import("node_modules/@tanstack/react-query/build/modern").UseMutationResult<WagglePreset, Error, WagglePreset, unknown>;
export declare function useDeleteWagglePresetMutation(projectPath: string | null): import("node_modules/@tanstack/react-query/build/modern").UseMutationResult<void, Error, WagglePresetId, unknown>;
export {};
