import { TIME_UNIT } from './time'

export const OPENWAGGLE_EXTENSION = {
  MANIFEST_FILE: 'openwaggle.extension.json',
  SDK_VERSION: '0.1.0',
  PROJECT_ROOT_SEGMENTS: ['.openwaggle', 'extensions'] as const,
  GLOBAL_EXTENSIONS_DIR: 'extensions',
  SCOPE: {
    GLOBAL_KIND: 'global',
    PROJECT_KIND: 'project',
    GLOBAL_ID: 'global',
  },
  PROJECT_OVERRIDE: {
    DISABLED_LABEL: 'Project disabled',
    ACTIVE_LABEL: 'Project active',
    DISABLE_ACTION_LABEL: 'Disable for project',
    ENABLE_ACTION_LABEL: 'Enable for project',
    REQUIRED_PROJECT_PATH_ERROR: 'Project path is required to set a project extension override.',
  },
  LIFECYCLE: {
    UPDATE_AVAILABLE_LABEL: 'Update available',
    BUILD_APPROVAL_REQUIRED_LABEL: 'Build approval required',
    BUILD_APPROVED_LABEL: 'Build approved',
    BUILD_SUCCEEDED_LABEL: 'Build succeeded',
    BUILD_FAILED_LABEL: 'Build failed',
    RELOAD_ACTION_LABEL: 'Reload',
    RELOAD_SUCCEEDED_LABEL: 'Reloaded',
    RELOAD_FAILED_LABEL: 'Reload failed',
    APPROVE_UPDATE_ACTION_LABEL: 'Approve update',
    APPROVE_BUILD_ACTION_LABEL: 'Approve and build',
    NO_UPDATE_AVAILABLE_ERROR: 'No extension update is available.',
    UNTRUSTED_UPDATE_ERROR: 'Trust this extension before approving updates.',
    APPROVE_UPDATE_REQUIRED_ERROR:
      'Approve the extension update before trusting the changed package.',
    NO_BUILD_APPROVAL_REQUIRED_ERROR: 'No local build approval is required for this extension.',
    BUILD_APPROVAL_UNAVAILABLE_ERROR:
      'Build approval is unavailable until the extension source files are valid.',
    BUILD_APPROVAL_REQUIRED_ERROR: 'the local build plan has not been approved.',
    BUILD_COMMAND_UNAVAILABLE_ERROR: 'The approved local build command is unavailable.',
    BUILD_ARTIFACT_VALIDATION_ERROR:
      'The approved build completed, but declared build artifacts are still invalid.',
    RELOAD_DISABLED_ERROR: 'Enable this extension before reloading it.',
  },
  LIMITS: {
    ID_MAX_LENGTH: 96,
    CONTRIBUTION_ID_MAX_LENGTH: 128,
    NAME_MAX_LENGTH: 120,
    DESCRIPTION_MAX_LENGTH: 2_000,
    RELATIVE_PATH_MAX_LENGTH: 260,
    BUILD_COMMAND_MAX_LENGTH: 500,
    BUILD_LOG_MAX_LENGTH: 4_000,
    BUILD_COMMAND_TIMEOUT_MS: TIME_UNIT.TEN_MINUTES_MS,
  },
  PATTERNS: {
    WINDOWS_ABSOLUTE_PATH: /^[A-Za-z]:[\\/]/,
    ID: /^[a-z0-9][a-z0-9._-]*$/,
    CONTRIBUTION_ID: /^[a-z0-9][a-z0-9._/-]*$/,
    SEMVER_VERSION:
      /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/,
    SEMVER_CORE: /^(\d+)\.(\d+)\.(\d+)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/,
    SEMVER_COMPARATOR: /^(>=|>|<=|<|=)?(.+)$/,
  },
  SEMVER_MATCH: {
    MAJOR: 1,
    MINOR: 2,
    PATCH: 3,
    COMPARATOR_OPERATOR: 1,
    COMPARATOR_VERSION: 2,
  },
  PATH: {
    NUL_CHARACTER: '\0',
    POSIX_SEPARATOR: '/',
    WINDOWS_SEPARATOR: '\\',
    RELATIVE_PARENT_SEGMENT: '..',
    CURRENT_DIRECTORY_SEGMENT: '.',
  },
  CAPABILITY_SCOPES: ['app', 'project', 'session', 'branch'] as const,
  UI_LANES: ['declarative', 'webview', 'trusted-react'] as const,
  CONTRIBUTION_FAMILIES: [
    'commands',
    'slashCommands',
    'routes',
    'settingsSections',
    'sidePanels',
    'dialogs',
    'transcriptRenderers',
    'statusWidgets',
  ] as const,
  ENTRY_CONTRIBUTION_FAMILIES: [
    'routes',
    'settingsSections',
    'sidePanels',
    'dialogs',
    'transcriptRenderers',
    'statusWidgets',
  ] as const,
  DIAGNOSTIC: {
    SEVERITIES: ['error', 'warning'] as const,
    CODE: {
      RUNTIME_LOAD_FAILED: 'runtime-load-failed',
    },
    BUILD_BLOCKING_CODES: [
      'source-file-missing',
      'built-artifact-missing',
      'runtime-file-missing',
      'build-command-missing',
      'build-output-not-artifact',
      'package-path-invalid',
      'filesystem-error',
    ] as const,
    CODES: [
      'manifest-missing',
      'manifest-json-invalid',
      'manifest-schema-invalid',
      'manifest-id-mismatch',
      'source-file-missing',
      'built-artifact-missing',
      'runtime-file-missing',
      'build-command-missing',
      'build-output-not-artifact',
      'build-failed',
      'build-artifacts-invalid',
      'package-path-invalid',
      'sdk-range-invalid',
      'sdk-incompatible',
      'runtime-load-failed',
      'filesystem-error',
    ] as const,
  },
  HASH: {
    ALGORITHM: 'sha256',
    ENCODING: 'hex',
    HEX_LENGTH: 64,
    FIELD_SEPARATOR: '\0',
    MANIFEST_LABEL: 'manifest',
    ARTIFACT_LABEL: 'artifact',
    BUILD_PLAN_LABEL: 'build-plan',
    SOURCE_LABEL: 'source',
    BUILD_COMMAND_LABEL: 'build-command',
  },
  LABELS: {
    SOURCE_FILE: 'source file',
    BUILT_ARTIFACT: 'built artifact',
    RUNTIME_FILE: 'runtime file',
    BUILD_OUTPUT: 'build output',
  },
  INSTALL_SOURCE: {
    PREBUILT: 'prebuilt',
    LOCAL_BUILD: 'local-build',
  },
  INSTALL_SOURCES: ['prebuilt', 'local-build'] as const,
  BUILD_RUN_STATUS: {
    NOT_RUN: 'not-run',
    SUCCEEDED: 'succeeded',
    FAILED: 'failed',
  },
  BUILD_RUN_STATUSES: ['not-run', 'succeeded', 'failed'] as const,
  RELOAD_STATUS: {
    NOT_RELOADED: 'not-reloaded',
    SUCCEEDED: 'succeeded',
    FAILED: 'failed',
  },
  RELOAD_STATUSES: ['not-reloaded', 'succeeded', 'failed'] as const,
} as const
