export const OPENWAGGLE_EXTENSION = {
  MANIFEST_FILE: 'openwaggle.extension.json',
  SDK_VERSION: '0.1.0',
  PROJECT_ROOT_SEGMENTS: ['.openwaggle', 'extensions'] as const,
  GLOBAL_EXTENSIONS_DIR: 'extensions',
  SCOPE: {
    GLOBAL_KIND: 'global',
    PROJECT_KIND: 'project',
    GLOBAL_ID: 'global',
  },
  PROJECT_OVERRIDE: {
    DISABLED_LABEL: 'Project disabled',
    ACTIVE_LABEL: 'Project active',
    DISABLE_ACTION_LABEL: 'Disable for project',
    ENABLE_ACTION_LABEL: 'Enable for project',
    REQUIRED_PROJECT_PATH_ERROR: 'Project path is required to set a project extension override.',
  },
  LIMITS: {
    ID_MAX_LENGTH: 96,
    CONTRIBUTION_ID_MAX_LENGTH: 128,
    NAME_MAX_LENGTH: 120,
    DESCRIPTION_MAX_LENGTH: 2_000,
    RELATIVE_PATH_MAX_LENGTH: 260,
  },
  PATTERNS: {
    WINDOWS_ABSOLUTE_PATH: /^[A-Za-z]:[\\/]/,
    ID: /^[a-z0-9][a-z0-9._-]*$/,
    CONTRIBUTION_ID: /^[a-z0-9][a-z0-9._/-]*$/,
    SEMVER_VERSION:
      /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/,
    SEMVER_CORE: /^(\d+)\.(\d+)\.(\d+)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/,
    SEMVER_COMPARATOR: /^(>=|>|<=|<|=)?(.+)$/,
  },
  SEMVER_MATCH: {
    MAJOR: 1,
    MINOR: 2,
    PATCH: 3,
    COMPARATOR_OPERATOR: 1,
    COMPARATOR_VERSION: 2,
  },
  PATH: {
    NUL_CHARACTER: '\0',
    POSIX_SEPARATOR: '/',
    WINDOWS_SEPARATOR: '\\',
    RELATIVE_PARENT_SEGMENT: '..',
    CURRENT_DIRECTORY_SEGMENT: '.',
  },
  CAPABILITY_SCOPES: ['app', 'project', 'session', 'branch'] as const,
  UI_LANES: ['declarative', 'webview', 'trusted-react'] as const,
  CONTRIBUTION_FAMILIES: [
    'commands',
    'slashCommands',
    'routes',
    'settingsSections',
    'sidePanels',
    'dialogs',
    'transcriptRenderers',
    'statusWidgets',
  ] as const,
  ENTRY_CONTRIBUTION_FAMILIES: [
    'routes',
    'settingsSections',
    'sidePanels',
    'dialogs',
    'transcriptRenderers',
    'statusWidgets',
  ] as const,
  DIAGNOSTIC: {
    SEVERITIES: ['error', 'warning'] as const,
    CODES: [
      'manifest-missing',
      'manifest-json-invalid',
      'manifest-schema-invalid',
      'manifest-id-mismatch',
      'source-file-missing',
      'built-artifact-missing',
      'runtime-file-missing',
      'package-path-invalid',
      'sdk-range-invalid',
      'sdk-incompatible',
      'filesystem-error',
    ] as const,
  },
  HASH: {
    ALGORITHM: 'sha256',
    ENCODING: 'hex',
    HEX_LENGTH: 64,
    FIELD_SEPARATOR: '\0',
    MANIFEST_LABEL: 'manifest',
    ARTIFACT_LABEL: 'artifact',
  },
  LABELS: {
    SOURCE_FILE: 'source file',
    BUILT_ARTIFACT: 'built artifact',
    RUNTIME_FILE: 'runtime file',
  },
} as const
