export const MCP_LATEST_PROTOCOL_VERSION = '2026-07-28'

export const MCP_MODERN_PROTOCOL_VERSIONS = [MCP_LATEST_PROTOCOL_VERSION] as const

export const MCP_LEGACY_PROTOCOL_VERSIONS = [
  '2025-11-25',
  '2025-06-18',
  '2025-03-26',
  '2024-11-05',
  '2024-10-07',
] as const

export const MCP_SUPPORTED_PROTOCOL_VERSIONS = [
  ...MCP_MODERN_PROTOCOL_VERSIONS,
  ...MCP_LEGACY_PROTOCOL_VERSIONS,
] as const

export const MCP_SKILLS_EXTENSION_ID = 'io.modelcontextprotocol/skills'

export const MCP_CONFIG = {
  JSON_INDENT_SPACES: 2,
  CONFIG_HASH_PREFIX_LENGTH: 24,
  GLOBAL_CONFIG_DIR: ['.openwaggle'],
  GLOBAL_CONFIG_FILE_NAME: 'mcp.json',
  GLOBAL_STATE_DIR: ['.openwaggle', 'mcp'],
  GLOBAL_STATE_FILE_NAME: 'state.json',
  GLOBAL_VAULT_FILE_NAME: 'vault.json',
  GLOBAL_TASK_FILE_NAME: 'tasks.json',
  PROJECT_STANDARD_CONFIG_FILE_NAME: '.mcp.json',
  PROJECT_OPENWAGGLE_CONFIG_DIR: ['.openwaggle'],
  PROJECT_OPENWAGGLE_CONFIG_FILE_NAME: 'mcp.json',
  EMPTY_CONFIG_RAW_JSON: '{\n  "mcpServers": {}\n}\n',
  STATE_VERSION: 1,
  CATALOG_CACHE_TTL_MS: 300_000,
  REQUEST_TIMEOUT_MS: 60_000,
  CONNECT_TIMEOUT_MS: 15_000,
  PROBE_TIMEOUT_MS: 3_000,
  MAX_LIST_PAGES: 64,
  MAX_INPUT_REQUIRED_ROUNDS: 8,
  MAX_GATEWAY_RESULTS: 40,
  MAX_RESULT_BYTES: 1_000_000,
  MAX_STDERR_BYTES: 128_000,
  MAX_CONCURRENT_CALLS: 8,
  MAX_ORCHESTRATION_CALLS: 32,
  MAX_ORCHESTRATION_DEPTH: 8,
  MAX_ORCHESTRATION_STEPS: 10_000,
  MAX_ORCHESTRATION_WALL_TIME_MS: 120_000,
  MAX_ORCHESTRATION_SOURCE_BYTES: 64_000,
  MAX_ORCHESTRATION_MEMORY_BYTES: 4_000_000,
  MAX_ORCHESTRATION_OUTPUT_BYTES: 1_000_000,
  MAX_SESSION_FAN_OUT: 8,
  MAX_EVENT_INBOX_ITEMS: 200,
  MAX_SERVER_INSTRUCTIONS_BYTES: 128_000,
  MAX_REMOTE_SKILLS: 2_000,
  MAX_REMOTE_SKILL_RESOURCES: 10_000,
} as const
