export {
  type ExtensionCapabilityDeclaration,
  type ExtensionCommandContribution,
  type ExtensionContributionRegistration,
  type ExtensionContributions,
  type ExtensionContributionUnregistration,
  type ExtensionEntryContribution,
  extensionCapabilityDeclarationSchema,
  extensionCapabilityScopeSchema,
  extensionCommandContributionFamilySchema,
  extensionCommandContributionRegistrationSchema,
  extensionCommandContributionSchema,
  extensionContributionFamilySchema,
  extensionContributionIdSchema,
  extensionContributionRegistrationSchema,
  extensionContributionRuntimeSchema,
  extensionContributionsSchema,
  extensionContributionUnregistrationSchema,
  extensionExecutionPlacementSchema,
  extensionRelativePathSchema,
  extensionRouteContributionRegistrationSchema,
  extensionRouteContributionSchema,
  extensionSlotContributionFamilySchema,
  extensionSlotContributionRegistrationSchema,
  extensionSlotContributionSchema,
} from '@openwaggle/extension-sdk'
