export {
  type ExtensionCapabilityDeclaration,
  type ExtensionCommandContribution,
  type ExtensionContributionRegistration,
  type ExtensionContributions,
  type ExtensionContributionUnregistration,
  type ExtensionEntryContribution,
  type ExtensionSessionSummaryContribution,
  type ExtensionSidePanelContribution,
  type ExtensionSidePanelIcon,
  extensionCapabilityDeclarationSchema,
  extensionCapabilityScopeSchema,
  extensionCommandContributionFamilySchema,
  extensionCommandContributionRegistrationSchema,
  extensionCommandContributionSchema,
  extensionContributionFamilySchema,
  extensionContributionIdSchema,
  extensionContributionRegistrationSchema,
  extensionContributionRuntimeSchema,
  extensionContributionsSchema,
  extensionContributionUnregistrationSchema,
  extensionExecutionPlacementSchema,
  extensionRelativePathSchema,
  extensionRouteContributionRegistrationSchema,
  extensionRouteContributionSchema,
  extensionSessionSummaryActionSchema,
  extensionSessionSummaryContributionRegistrationSchema,
  extensionSessionSummaryContributionSchema,
  extensionSessionSummaryDisclosureSchema,
  extensionSessionSummaryRowSchema,
  extensionSessionSummaryStateSchema,
  extensionSidePanelContributionRegistrationSchema,
  extensionSidePanelContributionSchema,
  extensionSidePanelIconSchema,
  extensionSlotContributionFamilySchema,
  extensionSlotContributionRegistrationSchema,
  extensionSlotContributionSchema,
} from '@openwaggle/extension-sdk'
