import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { generateDisplayName } from '@shared/types/llm';
import { Plus, Save, Trash2 } from 'lucide-react';
import { AGENT_BG } from '@/features/waggle/lib';
import { cn } from '@/shared/lib/cn';
import { Button } from '@/shared/ui/Button';
export function WagglePresetsPanel({ presets, activePresetId, isModified, onLoadPreset, onDeletePreset, onSaveEdits, onNewCustom, }) {
    return (_jsxs("div", { className: "rounded-lg border border-border bg-[#111418] p-5", children: [_jsx("h3", { className: "text-sm font-medium text-text-secondary mb-4", children: "Waggle Presets" }), _jsx("div", { className: "grid grid-cols-2 gap-3", children: presets.map((preset) => (_jsx(WagglePresetCard, { preset: preset, isActive: activePresetId === preset.id, isActiveModified: activePresetId === preset.id && isModified, onSelect: () => onLoadPreset(preset), onDelete: () => onDeletePreset(preset.id) }, preset.id))) }), _jsxs("div", { className: "mt-3 flex gap-2", children: [isModified && (_jsxs(Button, { variant: "unstyled", type: "button", onClick: () => void onSaveEdits(), className: "flex flex-1 items-center justify-center gap-1.5 rounded-lg border border-accent/30 bg-accent/5 p-2.5 text-[12px] font-medium text-accent hover:bg-accent/10 transition-colors", children: [_jsx(Save, { className: "size-3" }), "Save Changes"] })), _jsxs(Button, { variant: "unstyled", type: "button", onClick: () => void onNewCustom(), className: "flex flex-1 items-center justify-center gap-1.5 rounded-lg border border-dashed border-border p-2.5 text-[12px] font-medium text-text-muted hover:border-border-light hover:text-text-secondary transition-colors", children: [_jsx(Plus, { className: "size-3" }), "New Custom Preset"] })] })] }));
}
function WagglePresetCard({ preset, isActive, isActiveModified, onSelect, onDelete, }) {
    return (_jsx(Button, { variant: "unstyled", type: "button", className: cn('rounded-lg border p-3 cursor-pointer transition-colors text-left', isActive && !isActiveModified && 'border-accent/40 bg-accent/5', isActiveModified && 'border-accent/20 bg-accent/5', !isActive && 'border-border bg-bg hover:border-border-light'), onClick: onSelect, children: _jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { className: "min-w-0", children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx("span", { className: "text-[13px] font-medium text-text-primary truncate", children: preset.name }), _jsx("span", { className: "shrink-0 rounded px-1.5 py-0.5 text-[10px] font-medium bg-bg-tertiary text-text-muted", children: "Sequential" }), !preset.isBuiltIn && (_jsx("span", { className: "shrink-0 rounded px-1.5 py-0.5 text-[10px] font-medium bg-accent/10 text-accent", children: "Custom" })), isActiveModified && (_jsx("span", { className: "shrink-0 rounded px-1.5 py-0.5 text-[10px] font-medium bg-blue-500/10 text-blue-400", children: "Edited" }))] }), _jsx("p", { className: "text-[12px] text-text-tertiary line-clamp-2", children: preset.description }), _jsxs("div", { className: "mt-1.5 flex items-center gap-1.5 text-[11px] text-text-muted", children: [_jsx("div", { className: cn('size-1.5 rounded-full', AGENT_BG[preset.config.agents[0].color]) }), _jsx("span", { className: "truncate", children: generateDisplayName(preset.config.agents[0].model) }), _jsx("span", { className: "text-text-tertiary", children: "vs" }), _jsx("div", { className: cn('size-1.5 rounded-full', AGENT_BG[preset.config.agents[1].color]) }), _jsx("span", { className: "truncate", children: generateDisplayName(preset.config.agents[1].model) })] })] }), !preset.isBuiltIn && (_jsx("span", { role: "none", onClick: (event) => {
                        event.stopPropagation();
                        void onDelete();
                    }, onKeyDown: (event) => {
                        if (event.key === 'Enter' || event.key === ' ') {
                            event.stopPropagation();
                            void onDelete();
                        }
                    }, className: "p-1 rounded text-text-muted hover:text-error transition-colors cursor-pointer", children: _jsx(Trash2, { className: "size-3" }) }))] }) }));
}
