/**
 * One-off QA seed for ADR 0033 turn settle-fold (run with the app closed).
 * Seeds one session with two settled turns plus turn_checkpoints rows so the
 * fold rows, duration labels, and changed-files card render from real data.
 *
 *   pnpm exec tsx scripts/qa/seed-turn-fold-qa.ts
 */
import { seedSessions } from '../../e2e/support/session-fixtures'
import os from 'node:os'
import path from 'node:path'
import { DatabaseSync } from 'node:sqlite'

const USER_DATA_DIR =
  process.env.OPENWAGGLE_USER_DATA_DIR ?? path.join(os.homedir(), 'Library', 'Application Support', 'openwaggle')

const WORKTREE = '/Users/diego.garciabrisa/.openwaggle/worktrees/OpenWaggle/01a0b5c9-a152-7292-ab97-f79aead8f272'

const now = Date.now()
const MINUTE = 60_000
const TURN_ONE_DURATION_MS = 12_000
const TURN_TWO_DURATION_MS = 4_000
const TURN_TWO_AGE_MS = 60_000
const TURN_ONE_AGE_MS = TURN_TWO_AGE_MS + TURN_TWO_AGE_MS
const TOOL_RESULT_DURATION_MS = 120
const TURN_ONE_INDEX = 1
const TURN_TWO_INDEX = 2
const DIFF_INSERTIONS = 15
const DIFF_DELETIONS = 3

const SESSION_ID = 'turn-fold-qa-session'
const BRANCH_ID = `${SESSION_ID}:main`
const U1 = 'tfqa-user-1'
const A1 = 'tfqa-assistant-1'
const U2 = 'tfqa-user-2'
const A2 = 'tfqa-assistant-2'

const DIFF = [
  'diff --git a/src/greeting.ts b/src/greeting.ts',
  'index 1111111..2222222 100644',
  '--- a/src/greeting.ts',
  '+++ b/src/greeting.ts',
  '@@ -1,4 +1,14 @@',
  '-export const old = true',
  '+export function greet(name: string): string {',
  '+  return `Hello, ${name}!`',
  '+}',
  '+',
  '+export function farewell(name: string): string {',
  '+  return `Goodbye, ${name}!`',
  '+}',
  'diff --git a/src/index.ts b/src/index.ts',
  'index 3333333..4444444 100644',
  '--- a/src/index.ts',
  '+++ b/src/index.ts',
  '@@ -1,2 +1,4 @@',
  ' import {}',
  '+import { greet } from "./greeting"',
  '+console.log(greet("world"))',
].join('\n')

const sessions = [
  {
    title: 'Turn fold QA — settle folds',
    updatedAt: now,
    projectPath: WORKTREE,
    messages: [
      {
        id: U1,
        role: 'user',
        createdAt: now - TURN_ONE_AGE_MS - TURN_TWO_AGE_MS,
        parts: [{ type: 'text', text: 'Add a greeting module with greet and farewell helpers.' }],
      },
      {
        id: A1,
        role: 'assistant',
        createdAt: now - TURN_ONE_AGE_MS - TURN_TWO_DURATION_MS,
        parts: [
          { type: 'text', text: 'Creating the greeting module.' },
          {
            type: 'tool-call',
            toolCall: { id: 'tfqa-call-1', name: 'write_file', args: { path: 'src/greeting.ts' }, state: 'input-complete' },
          },
          {
            type: 'tool-result',
            toolResult: { id: 'tfqa-call-1', name: 'write_file', args: { path: 'src/greeting.ts' }, result: 'wrote src/greeting.ts', isError: false, duration: TOOL_RESULT_DURATION_MS },
          },
          { type: 'text', text: 'Added src/greeting.ts with greet and farewell helpers and wired them into src/index.ts.' },
        ],
      },
      {
        id: U2,
        role: 'user',
        createdAt: now - TURN_ONE_AGE_MS,
        parts: [{ type: 'text', text: 'Summarize what changed.' }],
      },
      {
        id: A2,
        role: 'assistant',
        createdAt: now - TURN_TWO_AGE_MS,
        parts: [
          {
            type: 'text',
            text:
              'Two files changed: src/greeting.ts adds greet/farewell helpers, src/index.ts imports and calls greet. Nothing else was touched.',
          },
        ],
      },
    ],
  },
]

// Idempotent: purge only rows this script created (fixed node ids / title), then reseed.
{
  const purge = new DatabaseSync(path.join(USER_DATA_DIR, 'openwaggle.db'))
  purge.exec('PRAGMA foreign_keys = ON')
  const stale = purge
    .prepare('SELECT id FROM sessions WHERE title = ? OR id IN (SELECT session_id FROM session_nodes WHERE id IN (?, ?, ?, ?))')
    .all('Turn fold QA — settle folds', U1, U2, A1, A2)
  for (const row of stale) {
    purge.prepare('DELETE FROM turn_checkpoints WHERE session_id = ?').run(row.id)
    purge.prepare('DELETE FROM session_branches WHERE session_id = ?').run(row.id)
    purge.prepare('DELETE FROM session_nodes WHERE session_id = ?').run(row.id)
    purge.prepare('DELETE FROM sessions WHERE id = ?').run(row.id)
  }
  purge.close()
}
void seedSessions(USER_DATA_DIR, sessions).then(() => { main() })

// Attach turn checkpoints with durations + diffs. anchor_node_id = terminal assistant node id.
function main() {
const database = new DatabaseSync(path.join(USER_DATA_DIR, 'openwaggle.db'))
database.exec('PRAGMA foreign_keys = ON')
// session id/branch id are generated by seedSessions; look them up by title
const sessionRow = database
  .prepare('SELECT id FROM sessions WHERE title = ? ORDER BY updated_at DESC LIMIT 1')
  .get('Turn fold QA — settle folds')
if (!sessionRow) throw new Error('seeded session not found')
const sessionId = sessionRow.id
const branchId = `${sessionId}:main`

const checkpoints = [
  {
    turnId: 'turn-1',
    turnIndex: TURN_ONE_INDEX,
    createdAt: now - TURN_ONE_AGE_MS - TURN_TWO_DURATION_MS,
    startedAt: now - TURN_ONE_AGE_MS - TURN_TWO_DURATION_MS - TURN_ONE_DURATION_MS,
    anchorNodeId: A1,
    branchId,
  },
  {
    turnId: 'turn-2',
    turnIndex: TURN_TWO_INDEX,
    createdAt: now - TURN_TWO_AGE_MS,
    startedAt: now - TURN_TWO_AGE_MS - TURN_TWO_DURATION_MS,
    anchorNodeId: A2,
    branchId,
  },
]

// Older dev databases predate migration 28 (turn-checkpoint started_at); apply it idempotently.
const columns = database.prepare('PRAGMA table_info(turn_checkpoints)').all().map((col) => col.name)
if (!columns.includes('started_at')) {
  database.exec('ALTER TABLE turn_checkpoints ADD COLUMN started_at INTEGER')
}

const insert = database.prepare(`
  INSERT INTO turn_checkpoints (id, session_id, turn_id, turn_index, created_at, started_at, diff, insertions, deletions, anchor_node_id)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  ON CONFLICT(id) DO NOTHING
`)

for (const checkpoint of checkpoints) {
  insert.run(
    `${sessionId}:${checkpoint.turnId}`,
    sessionId,
    checkpoint.turnId,
    checkpoint.turnIndex,
    checkpoint.createdAt,
    checkpoint.startedAt,
    DIFF,
    DIFF_INSERTIONS,
    DIFF_DELETIONS,
    checkpoint.anchorNodeId,
  )
}

const verify = database
  .prepare('SELECT turn_id, turn_index, started_at, insertions, deletions FROM turn_checkpoints WHERE session_id = ?')
  .all(sessionId)
console.log('SEEDED', JSON.stringify({ sessionId, checkpoints: verify }))
database.close()
}
