/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as SkillsRouteImport } from './routes/skills';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as ChatRouteImport } from './routes/_chat';
import { Route as ChatIndexRouteImport } from './routes/_chat.index';
import { Route as SettingsTabRouteImport } from './routes/settings.$tab';
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId';
import { Route as ExtensionsExtensionIdSplatRouteImport } from './routes/extensions.$extensionId.$';
const SkillsRoute = SkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => rootRouteImport,
});
const SettingsRoute = SettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => rootRouteImport,
});
const ChatRoute = ChatRouteImport.update({
    id: '/_chat',
    getParentRoute: () => rootRouteImport,
});
const ChatIndexRoute = ChatIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ChatRoute,
});
const SettingsTabRoute = SettingsTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => SettingsRoute,
});
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
});
const ExtensionsExtensionIdSplatRoute = ExtensionsExtensionIdSplatRouteImport.update({
    id: '/extensions/$extensionId/$',
    path: '/extensions/$extensionId/$',
    getParentRoute: () => rootRouteImport,
});
const ChatRouteChildren = {
    ChatIndexRoute: ChatIndexRoute,
};
const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren);
const SettingsRouteChildren = {
    SettingsTabRoute: SettingsTabRoute,
};
const SettingsRouteWithChildren = SettingsRoute._addFileChildren(SettingsRouteChildren);
const rootRouteChildren = {
    ChatRoute: ChatRouteWithChildren,
    SettingsRoute: SettingsRouteWithChildren,
    SkillsRoute: SkillsRoute,
    SessionsSessionIdRoute: SessionsSessionIdRoute,
    ExtensionsExtensionIdSplatRoute: ExtensionsExtensionIdSplatRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
