import {
  SESSION_EXPORT_FORMATS,
  SESSION_EXPORT_OPERATION_STATUSES,
} from '@shared/types/session-export-operation'
import { SESSION_QUERY_WAIT_TARGET_LIMIT } from '@shared/types/session-query'
import { z } from 'zod'
import {
  booleanFlag,
  boundedCursor,
  catalogScope,
  discoveryLimit,
  idempotency,
  interactionResponseSchema,
  interactionTimeout,
  newWorktreeFields,
  operationSchema,
  revision,
  runAuthorization,
  searchMode,
  specialization,
  timeout,
  transcriptLimit,
} from './openwaggle-mcp-session-input-schema-shared-v2'
import {
  MCP_SESSION_INPUT_LIMITS_V2,
  mcpSessionIdSchemaV2,
  mcpSessionItemArraySchemaV2,
  mcpSessionPathSchemaV2,
  mcpSessionResourceReferencesSchemaV2,
  mcpSessionTextSchemaV2,
  mcpSessionTitleSchemaV2,
} from './openwaggle-mcp-session-resource-envelope-v2'

export const mcpSessionQueryLifecycleOperationSchemasV2 = [
  operationSchema('list', {
    projectPath: mcpSessionPathSchemaV2.optional(),
    catalogScope: catalogScope.optional(),
    archived: booleanFlag.optional(),
    limit: discoveryLimit.optional(),
    cursor: boundedCursor.optional(),
  }),
  operationSchema('search', {
    message: mcpSessionTextSchemaV2.optional(),
    projectPath: mcpSessionPathSchemaV2.optional(),
    catalogScope: catalogScope.optional(),
    limit: discoveryLimit.optional(),
    cursor: boundedCursor.optional(),
    fullTranscript: booleanFlag.optional(),
    includeArchived: booleanFlag.optional(),
    searchMode: searchMode.optional(),
    requireFresh: booleanFlag.optional(),
    timeoutMs: timeout.optional(),
  }),
  operationSchema('read', { sessionId: mcpSessionIdSchemaV2.optional() }),
  operationSchema('turns', {
    sessionId: mcpSessionIdSchemaV2.optional(),
    limit: discoveryLimit.optional(),
    cursor: boundedCursor.optional(),
  }),
  operationSchema('items', {
    sessionId: mcpSessionIdSchemaV2.optional(),
    runId: mcpSessionIdSchemaV2.optional(),
    afterCreatedOrder: revision.optional(),
    limit: transcriptLimit.optional(),
  }),
  operationSchema('status', { sessionId: mcpSessionIdSchemaV2.optional() }),
  operationSchema('export', {
    sessionId: mcpSessionIdSchemaV2.optional(),
    exportFormat: z.enum(SESSION_EXPORT_FORMATS).optional(),
    branchScope: z.enum(['active-branch', 'tree']).optional(),
    branchId: mcpSessionIdSchemaV2.optional(),
    includeQueueBodies: booleanFlag.optional(),
    limit: transcriptLimit.optional(),
  }),
  operationSchema('export-create', {
    sessionId: mcpSessionIdSchemaV2.optional(),
    destinationPath: mcpSessionPathSchemaV2.optional(),
    exportFormat: z.enum(SESSION_EXPORT_FORMATS).optional(),
    branchScope: z.enum(['active-branch', 'tree']).optional(),
    branchId: mcpSessionIdSchemaV2.optional(),
    includeQueueBodies: booleanFlag.optional(),
    overwriteExisting: booleanFlag.optional(),
    exportResources: mcpSessionResourceReferencesSchemaV2.optional(),
    ...idempotency,
  }),
  operationSchema('export-cancel', {
    sessionId: mcpSessionIdSchemaV2.optional(),
    exportOperationId: mcpSessionIdSchemaV2.optional(),
    ...idempotency,
  }),
  operationSchema('exports-list', {
    sessionId: mcpSessionIdSchemaV2.optional(),
    exportStatuses: z
      .array(z.enum(SESSION_EXPORT_OPERATION_STATUSES))
      .max(MCP_SESSION_INPUT_LIMITS_V2.arrayItems)
      .optional(),
    limit: discoveryLimit.optional(),
    cursor: boundedCursor.optional(),
  }),
  operationSchema('exports-read', {
    sessionId: mcpSessionIdSchemaV2.optional(),
    exportOperationId: mcpSessionIdSchemaV2.optional(),
  }),
  operationSchema('exports-wait', {
    sessionId: mcpSessionIdSchemaV2.optional(),
    exportOperationId: mcpSessionIdSchemaV2.optional(),
    timeoutMs: timeout.optional(),
  }),
  operationSchema('requests-list', { sessionId: mcpSessionIdSchemaV2.optional() }),
  operationSchema('request-respond', {
    sessionId: mcpSessionIdSchemaV2.optional(),
    runId: mcpSessionIdSchemaV2.optional(),
    interactionId: mcpSessionIdSchemaV2.optional(),
    interactionResponse: interactionResponseSchema.optional(),
    ...idempotency,
  }),
  operationSchema('approval-respond', {
    sessionId: mcpSessionIdSchemaV2.optional(),
    runId: mcpSessionIdSchemaV2.optional(),
    interactionId: mcpSessionIdSchemaV2.optional(),
    interactionResponse: interactionResponseSchema.optional(),
    ...idempotency,
  }),
  operationSchema('authorization-set', {
    sessionId: mcpSessionIdSchemaV2.optional(),
    authorizationMode: z.enum(['inherit', 'ask-for-approval', 'yolo']).optional(),
    ...idempotency,
  }),
  operationSchema('rename', {
    sessionId: mcpSessionIdSchemaV2.optional(),
    title: mcpSessionTitleSchemaV2.optional(),
    ...idempotency,
  }),
  operationSchema('archive', { sessionId: mcpSessionIdSchemaV2.optional(), ...idempotency }),
  operationSchema('unarchive', { sessionId: mcpSessionIdSchemaV2.optional(), ...idempotency }),
  operationSchema('handoff', {
    sessionId: mcpSessionIdSchemaV2.optional(),
    workspace: z.enum(['local', 'existing', 'new-worktree']).optional(),
    workspaceId: mcpSessionIdSchemaV2.optional(),
    ...newWorktreeFields,
    ...idempotency,
  }),
  operationSchema('wait', {
    sessionIds: z.array(mcpSessionIdSchemaV2).max(SESSION_QUERY_WAIT_TARGET_LIMIT).optional(),
    sessionId: mcpSessionIdSchemaV2.optional(),
    condition: z.enum(['idle', 'queue-empty', 'state-revision-after']).optional(),
    afterStateRevision: revision.optional(),
    timeoutMs: timeout.optional(),
  }),
  operationSchema('create', {
    projectPath: mcpSessionPathSchemaV2.optional(),
    title: mcpSessionTitleSchemaV2.optional(),
    workspace: z.enum(['current', 'local', 'existing', 'new-worktree']).optional(),
    workspaceId: mcpSessionIdSchemaV2.optional(),
    ...newWorktreeFields,
    ...specialization,
    ...idempotency,
  }),
  operationSchema('fork', {
    sessionId: mcpSessionIdSchemaV2.optional(),
    targetNodeId: mcpSessionIdSchemaV2.optional(),
    forkPosition: z.enum(['before', 'at']).optional(),
    title: mcpSessionTitleSchemaV2.optional(),
    workspace: z.enum(['share-source', 'local', 'existing', 'new-worktree']).optional(),
    workspaceId: mcpSessionIdSchemaV2.optional(),
    ...newWorktreeFields,
    ...idempotency,
  }),
  operationSchema('launch', {
    projectPath: mcpSessionPathSchemaV2.optional(),
    objective: mcpSessionTextSchemaV2.optional(),
    title: mcpSessionTitleSchemaV2.optional(),
    workspace: z.enum(['current', 'local', 'existing', 'new-worktree']).optional(),
    workspaceId: mcpSessionIdSchemaV2.optional(),
    ...newWorktreeFields,
    ...specialization,
    ...runAuthorization,
    interactionTimeoutMs: interactionTimeout.optional(),
    ...idempotency,
  }),
  operationSchema('spawn', {
    sessionId: mcpSessionIdSchemaV2.optional(),
    expectedRunId: mcpSessionIdSchemaV2.optional(),
    objective: mcpSessionTextSchemaV2.optional(),
    workspace: z.enum(['share-parent', 'local', 'new-worktree']).optional(),
    ...newWorktreeFields,
    ...specialization,
    deliverables: mcpSessionItemArraySchemaV2.optional(),
    acceptanceCriteria: mcpSessionItemArraySchemaV2.optional(),
    resourceReferences: mcpSessionResourceReferencesSchemaV2.optional(),
    ...runAuthorization,
    interactionTimeoutMs: interactionTimeout.optional(),
    ...idempotency,
  }),
] as const
