const TEN_MINUTES_MS = 10 * 60 * 1_000

const EXTENSION_BROKER_FAILURE_CODE = {
  INVALID_INPUT: 'invalid-input',
  INVALID_PAYLOAD: 'invalid-payload',
  UNKNOWN_EXTENSION: 'unknown-extension',
  DISABLED_EXTENSION: 'disabled-extension',
  UNKNOWN_CONTRIBUTION: 'unknown-contribution',
  UNDECLARED_CAPABILITY: 'undeclared-capability',
  UNDECLARED_METHOD: 'undeclared-method',
  UNDECLARED_SCOPE: 'undeclared-scope',
  OUT_OF_SCOPE: 'out-of-scope',
  UNSUPPORTED_CAPABILITY: 'unsupported-capability',
  UNSUPPORTED_METHOD: 'unsupported-method',
  TRANSPORT_FAILED: 'transport-failed',
} as const

const EXTENSION_BROKER_OUTCOME = {
  SUCCEEDED: 'succeeded',
  REJECTED: 'rejected',
} as const

const EXTENSION_BROKER_CAPABILITY = {
  HOST_CONTEXT: 'openwaggle.host.context',
  STORAGE: 'openwaggle.storage',
  STATE: 'openwaggle.state',
  ACTIONS: 'openwaggle.actions',
  SETTINGS: 'openwaggle.settings',
  DOCS: 'openwaggle.docs',
  RUNTIME: 'openwaggle.runtime',
} as const

const EXTENSION_BROKER_METHOD = {
  GET_SCOPE: 'get-scope',
  GET: 'get',
  SET: 'set',
  DELETE: 'delete',
  LIST: 'list',
  GET_STATE: 'get-state',
  READ_STATE: 'read-state',
  SELECT_PROJECT: 'select-project',
  GET_SETTINGS: 'get-settings',
  UPDATE_SETTINGS: 'update-settings',
  GET_SETTING: 'get-setting',
  UPDATE_SETTING: 'update-setting',
  DISCOVER_DOCS: 'discover-docs',
  RESOLVE_DOCS_TOPIC: 'resolve-docs-topic',
  REGISTER_CONTRIBUTION: 'register-contribution',
  UNREGISTER_CONTRIBUTION: 'unregister-contribution',
} as const

const EXTENSION_BROKER_STATE_SELECTOR = {
  CURRENT_PROJECT: 'current-project',
  CURRENT_SESSION: 'current-session',
  CURRENT_BRANCH: 'current-branch',
  RECENT_PROJECTS: 'recent-projects',
  MODEL_PREFERENCES: 'model-preferences',
} as const

const EXTENSION_BROKER_SETTING_KEY = {
  MODEL_PREFERENCES: 'model-preferences',
  PROJECT_DISPLAY_NAME: 'project-display-name',
} as const

const EXTENSION_BROKER_CAPABILITY_METHODS = [
  {
    capability: EXTENSION_BROKER_CAPABILITY.HOST_CONTEXT,
    methods: [EXTENSION_BROKER_METHOD.GET_SCOPE],
  },
  {
    capability: EXTENSION_BROKER_CAPABILITY.STORAGE,
    methods: [
      EXTENSION_BROKER_METHOD.GET,
      EXTENSION_BROKER_METHOD.SET,
      EXTENSION_BROKER_METHOD.DELETE,
      EXTENSION_BROKER_METHOD.LIST,
    ],
  },
  {
    capability: EXTENSION_BROKER_CAPABILITY.STATE,
    methods: [EXTENSION_BROKER_METHOD.GET_STATE, EXTENSION_BROKER_METHOD.READ_STATE],
  },
  {
    capability: EXTENSION_BROKER_CAPABILITY.ACTIONS,
    methods: [EXTENSION_BROKER_METHOD.SELECT_PROJECT],
  },
  {
    capability: EXTENSION_BROKER_CAPABILITY.SETTINGS,
    methods: [
      EXTENSION_BROKER_METHOD.GET_SETTINGS,
      EXTENSION_BROKER_METHOD.UPDATE_SETTINGS,
      EXTENSION_BROKER_METHOD.GET_SETTING,
      EXTENSION_BROKER_METHOD.UPDATE_SETTING,
    ],
  },
  {
    capability: EXTENSION_BROKER_CAPABILITY.DOCS,
    methods: [EXTENSION_BROKER_METHOD.DISCOVER_DOCS, EXTENSION_BROKER_METHOD.RESOLVE_DOCS_TOPIC],
  },
  {
    capability: EXTENSION_BROKER_CAPABILITY.RUNTIME,
    methods: [
      EXTENSION_BROKER_METHOD.REGISTER_CONTRIBUTION,
      EXTENSION_BROKER_METHOD.UNREGISTER_CONTRIBUTION,
    ],
  },
] as const

const EXTENSION_CONTRIBUTION_FAMILY = {
  COMMANDS: 'commands',
  SLASH_COMMANDS: 'slashCommands',
  ROUTES: 'routes',
  SETTINGS_SECTIONS: 'settingsSections',
  SIDE_PANELS: 'sidePanels',
  DIALOGS: 'dialogs',
  TRANSCRIPT_RENDERERS: 'transcriptRenderers',
  TOOL_RENDERERS: 'toolRenderers',
  CUSTOM_MESSAGE_RENDERERS: 'customMessageRenderers',
  INTERACTION_RENDERERS: 'interactionRenderers',
  STATUS_WIDGETS: 'statusWidgets',
} as const

const EXTENSION_COMMAND_CONTRIBUTION_FAMILIES = Object.freeze([
  EXTENSION_CONTRIBUTION_FAMILY.COMMANDS,
  EXTENSION_CONTRIBUTION_FAMILY.SLASH_COMMANDS,
] as const)

const EXTENSION_SLOT_CONTRIBUTION_FAMILIES = Object.freeze([
  EXTENSION_CONTRIBUTION_FAMILY.SETTINGS_SECTIONS,
  EXTENSION_CONTRIBUTION_FAMILY.SIDE_PANELS,
  EXTENSION_CONTRIBUTION_FAMILY.DIALOGS,
  EXTENSION_CONTRIBUTION_FAMILY.TRANSCRIPT_RENDERERS,
  EXTENSION_CONTRIBUTION_FAMILY.TOOL_RENDERERS,
  EXTENSION_CONTRIBUTION_FAMILY.CUSTOM_MESSAGE_RENDERERS,
  EXTENSION_CONTRIBUTION_FAMILY.INTERACTION_RENDERERS,
  EXTENSION_CONTRIBUTION_FAMILY.STATUS_WIDGETS,
] as const)

const EXTENSION_ENTRY_CONTRIBUTION_FAMILIES = Object.freeze([
  EXTENSION_CONTRIBUTION_FAMILY.ROUTES,
  ...EXTENSION_SLOT_CONTRIBUTION_FAMILIES,
] as const)

const EXTENSION_CONTRIBUTION_FAMILIES = Object.freeze([
  ...EXTENSION_COMMAND_CONTRIBUTION_FAMILIES,
  ...EXTENSION_ENTRY_CONTRIBUTION_FAMILIES,
] as const)

const EXTENSION_CONTRIBUTION_RUNTIME = {
  FEDERATED_MODULE: 'federated-module',
  TRUSTED_RENDERER: 'trusted-renderer',
} as const

const EXTENSION_EXECUTION_PLACEMENT = {
  HOST_RENDERER: 'host-renderer',
  FRAME: 'frame',
} as const

const EXTENSION_STORAGE_KIND = {
  STATE: 'state',
  CONFIG: 'config',
} as const

const EXTENSION_STORAGE_SCOPE = {
  GLOBAL_KIND: 'global',
  PROJECT_KIND: 'project',
  GLOBAL_ID: 'global',
} as const

const EXTENSION_INSTALL_SOURCE = {
  PREBUILT: 'prebuilt',
  LOCAL_BUILD: 'local-build',
} as const

const EXTENSION_RUNTIME_REQUIREMENT_TYPE = {
  BINARY: 'binary',
  COMMAND: 'command',
} as const

const EXTENSION_NETWORK_ACCESS_MODE = {
  BROKERED: 'brokered',
  RESTRICTED: 'restricted',
  DIRECT: 'direct',
} as const

export const OPENWAGGLE_EXTENSION_BROKER = {
  CAPABILITY: EXTENSION_BROKER_CAPABILITY,
  CAPABILITIES: Object.freeze(Object.values(EXTENSION_BROKER_CAPABILITY)),
  CAPABILITY_METHODS: EXTENSION_BROKER_CAPABILITY_METHODS,
  METHOD: EXTENSION_BROKER_METHOD,
  METHODS: Object.freeze(Object.values(EXTENSION_BROKER_METHOD)),
  FAILURE_CODE: EXTENSION_BROKER_FAILURE_CODE,
  FAILURE_CODES: Object.freeze(Object.values(EXTENSION_BROKER_FAILURE_CODE)),
  OUTCOME: EXTENSION_BROKER_OUTCOME,
  OUTCOMES: Object.freeze(Object.values(EXTENSION_BROKER_OUTCOME)),
  STATE_SELECTOR: EXTENSION_BROKER_STATE_SELECTOR,
  STATE_SELECTORS: Object.freeze(Object.values(EXTENSION_BROKER_STATE_SELECTOR)),
  SETTING_KEY: EXTENSION_BROKER_SETTING_KEY,
  SETTING_KEYS: Object.freeze(Object.values(EXTENSION_BROKER_SETTING_KEY)),
} as const

export const OPENWAGGLE_EXTENSION = {
  MANIFEST_FILE: 'openwaggle.extension.json',
  SDK_VERSION: '0.1.0',
  PROJECT_ROOT_SEGMENTS: ['.openwaggle', 'extensions'] as const,
  GLOBAL_EXTENSIONS_DIR: 'extensions',
  SCOPE: {
    GLOBAL_KIND: 'global',
    PROJECT_KIND: 'project',
    GLOBAL_ID: 'global',
  },
  LIMITS: {
    ID_MAX_LENGTH: 96,
    CONTRIBUTION_ID_MAX_LENGTH: 128,
    NAME_MAX_LENGTH: 120,
    DESCRIPTION_MAX_LENGTH: 2_000,
    RELATIVE_PATH_MAX_LENGTH: 260,
    NETWORK_ORIGIN_MAX_LENGTH: 300,
    RUNTIME_REQUIREMENT_BINARY_MAX_LENGTH: 120,
    BUILD_COMMAND_MAX_LENGTH: 500,
    BUILD_LOG_MAX_LENGTH: 4_000,
    BUILD_COMMAND_TIMEOUT_MS: TEN_MINUTES_MS,
  },
  CAPABILITY_SCOPES: ['app', 'project', 'session', 'branch'] as const,
  CONTRIBUTION_FAMILY: EXTENSION_CONTRIBUTION_FAMILY,
  CONTRIBUTION_FAMILIES: EXTENSION_CONTRIBUTION_FAMILIES,
  COMMAND_CONTRIBUTION_FAMILIES: EXTENSION_COMMAND_CONTRIBUTION_FAMILIES,
  CONTRIBUTION_RUNTIME: EXTENSION_CONTRIBUTION_RUNTIME,
  CONTRIBUTION_RUNTIMES: Object.freeze(Object.values(EXTENSION_CONTRIBUTION_RUNTIME)),
  EXECUTION_PLACEMENT: EXTENSION_EXECUTION_PLACEMENT,
  EXECUTION_PLACEMENTS: Object.freeze(Object.values(EXTENSION_EXECUTION_PLACEMENT)),
  STORAGE: {
    KIND: EXTENSION_STORAGE_KIND,
    KINDS: Object.freeze(Object.values(EXTENSION_STORAGE_KIND)),
    SCOPE: EXTENSION_STORAGE_SCOPE,
    SCOPE_KINDS: Object.freeze([
      EXTENSION_STORAGE_SCOPE.GLOBAL_KIND,
      EXTENSION_STORAGE_SCOPE.PROJECT_KIND,
    ]),
    KEY_MAX_LENGTH: 160,
  },
  ENTRY_CONTRIBUTION_FAMILIES: EXTENSION_ENTRY_CONTRIBUTION_FAMILIES,
  SLOT_CONTRIBUTION_FAMILIES: EXTENSION_SLOT_CONTRIBUTION_FAMILIES,
  INSTALL_SOURCE: EXTENSION_INSTALL_SOURCE,
  INSTALL_SOURCES: Object.freeze(Object.values(EXTENSION_INSTALL_SOURCE)),
  RUNTIME_REQUIREMENT_TYPE: EXTENSION_RUNTIME_REQUIREMENT_TYPE,
  RUNTIME_REQUIREMENT_TYPES: Object.freeze(Object.values(EXTENSION_RUNTIME_REQUIREMENT_TYPE)),
  NETWORK_ACCESS_MODE: EXTENSION_NETWORK_ACCESS_MODE,
  NETWORK_ACCESS_MODES: Object.freeze(Object.values(EXTENSION_NETWORK_ACCESS_MODE)),
} as const
