export const SETTINGS_KEY_DEFAULT_MODEL = 'selectedModel'
export const SETTINGS_KEY_FAVORITE_MODELS = 'favoriteModels'
export const SETTINGS_KEY_PROJECT_PATH = 'projectPath'
export const SETTINGS_KEY_THINKING_LEVEL = 'thinkingLevel'
export const SETTINGS_KEY_RECENT_PROJECTS = 'recentProjects'
export const SETTINGS_KEY_SKILL_TOGGLES_BY_PROJECT = 'skillTogglesByProject'
export const SETTINGS_KEY_ENABLED_MODELS = 'enabledModels'
export const SETTINGS_KEY_PROJECT_DISPLAY_NAMES = 'projectDisplayNames'
export const SETTINGS_KEY_SHORTCUT_BINDINGS = 'shortcutBindings'
export const SETTINGS_KEY_SHORTCUT_RULES = 'shortcutRules'
export const SETTINGS_KEY_DEFAULT_SESSION_ENVIRONMENT_MODE = 'defaultSessionEnvironmentMode'
export const SETTINGS_KEY_DEFAULT_AUTHORIZATION_MODE = 'defaultAuthorizationMode'
export const SETTINGS_KEY_DIFF_SYNTAX_THEME = 'diffSyntaxTheme'
export const SETTINGS_KEY_SYNTAX_THEME_SELECTIONS = 'syntaxThemeSelections'
export const SETTINGS_KEY_DIFF_VIEW = 'diffView'
export const SETTINGS_KEY_DIFF_WRAP_LINES = 'diffWrapLines'
export const SETTINGS_KEY_APPEARANCE_PREFERENCES = 'appearancePreferences'
export const SETTINGS_KEY_BROWSER_LINK_TARGET = 'browserLinkTarget'
export const SETTINGS_KEY_BROWSER_PROFILES = 'browserProfiles'
export const SETTINGS_KEY_BROWSER_DEFAULT_PROFILE_ID = 'browserDefaultProfileId'
export const SETTINGS_KEY_BROWSER_DEFAULT_VIEWPORT = 'browserDefaultViewport'
export const SETTINGS_KEY_BROWSER_DEFAULT_ZOOM_FACTOR = 'browserDefaultZoomFactor'
export const SETTINGS_KEY_BROWSER_DEFAULT_APPEARANCE = 'browserDefaultAppearance'
export const SETTINGS_KEY_BROWSER_RECORDING_FRAME_RATE = 'browserRecordingFrameRate'
export const SETTINGS_KEY_BROWSER_AUTO_SHOW_FLOATING_PREVIEW = 'browserAutoShowFloatingPreview'
export const SETTINGS_KEY_ENABLE_AGENT_BROWSER_ACCESS = 'enableAgentBrowserAccess'

/** Known persisted fields. Unknown retired keys are ignored until an explicit migration removes them. */
export const CURRENT_SETTINGS_KEYS = [
  SETTINGS_KEY_DEFAULT_MODEL,
  SETTINGS_KEY_FAVORITE_MODELS,
  SETTINGS_KEY_PROJECT_PATH,
  SETTINGS_KEY_THINKING_LEVEL,
  SETTINGS_KEY_RECENT_PROJECTS,
  SETTINGS_KEY_SKILL_TOGGLES_BY_PROJECT,
  SETTINGS_KEY_ENABLED_MODELS,
  SETTINGS_KEY_PROJECT_DISPLAY_NAMES,
  SETTINGS_KEY_SHORTCUT_BINDINGS,
  SETTINGS_KEY_SHORTCUT_RULES,
  SETTINGS_KEY_DEFAULT_SESSION_ENVIRONMENT_MODE,
  SETTINGS_KEY_DEFAULT_AUTHORIZATION_MODE,
  SETTINGS_KEY_DIFF_SYNTAX_THEME,
  SETTINGS_KEY_SYNTAX_THEME_SELECTIONS,
  SETTINGS_KEY_DIFF_VIEW,
  SETTINGS_KEY_DIFF_WRAP_LINES,
  SETTINGS_KEY_APPEARANCE_PREFERENCES,
  SETTINGS_KEY_BROWSER_LINK_TARGET,
  SETTINGS_KEY_BROWSER_PROFILES,
  SETTINGS_KEY_BROWSER_DEFAULT_PROFILE_ID,
  SETTINGS_KEY_BROWSER_DEFAULT_VIEWPORT,
  SETTINGS_KEY_BROWSER_DEFAULT_ZOOM_FACTOR,
  SETTINGS_KEY_BROWSER_DEFAULT_APPEARANCE,
  SETTINGS_KEY_BROWSER_RECORDING_FRAME_RATE,
  SETTINGS_KEY_BROWSER_AUTO_SHOW_FLOATING_PREVIEW,
  SETTINGS_KEY_ENABLE_AGENT_BROWSER_ACCESS,
] as const
