export const SETTINGS_KEY_DEFAULT_MODEL = 'selectedModel'
export const SETTINGS_KEY_FAVORITE_MODELS = 'favoriteModels'
export const SETTINGS_KEY_PROJECT_PATH = 'projectPath'
export const SETTINGS_KEY_THINKING_LEVEL = 'thinkingLevel'
export const SETTINGS_KEY_RECENT_PROJECTS = 'recentProjects'
export const SETTINGS_KEY_SKILL_TOGGLES_BY_PROJECT = 'skillTogglesByProject'
export const SETTINGS_KEY_ENABLED_MODELS = 'enabledModels'
export const SETTINGS_KEY_PROJECT_DISPLAY_NAMES = 'projectDisplayNames'
export const SETTINGS_KEY_SHORTCUT_BINDINGS = 'shortcutBindings'
export const SETTINGS_KEY_DEFAULT_SESSION_ENVIRONMENT_MODE = 'defaultSessionEnvironmentMode'
export const SETTINGS_KEY_DEFAULT_AUTHORIZATION_MODE = 'defaultAuthorizationMode'
export const SETTINGS_KEY_DIFF_SYNTAX_THEME = 'diffSyntaxTheme'
export const SETTINGS_KEY_DIFF_VIEW = 'diffView'
export const SETTINGS_KEY_DIFF_WRAP_LINES = 'diffWrapLines'
export const SETTINGS_KEY_SESSION_HOST_PARENT_CONCURRENCY_LIMIT =
  'sessionHostParentConcurrencyLimit'
export const SETTINGS_KEY_SESSION_HOST_PARENT_CONCURRENCY_LIMITS_BY_PROJECT =
  'sessionHostParentConcurrencyLimitsByProject'
export const SETTINGS_KEY_SESSION_HOST_RUN_CEILING = 'sessionHostRunCeiling'
export const SETTINGS_KEY_SESSION_HOST_IDLE_GRACE_PERIOD_MS = 'sessionHostIdleGracePeriodMs'
export const SETTINGS_KEY_MULTI_AGENT_ENABLED = 'multiAgentEnabled'
export const SETTINGS_KEY_MULTI_AGENT_ENABLED_BY_PROJECT = 'multiAgentEnabledByProject'
