export { ExtensionAgentLoopStatusWidgets } from './components/ExtensionAgentLoopStatusWidgets';
export { CUSTOM_INTERACTION_RESPONSE_ACTION_ID, CUSTOM_INTERACTION_UNAVAILABLE_ACTION_ID, ExtensionAgentLoopSurface, } from './components/ExtensionAgentLoopSurface';
export { ExtensionContributionRuntimeHost } from './components/ExtensionContributionRuntimeHost';
export { ExtensionDialogSurface, ExtensionDialogSurfaceContent, } from './components/ExtensionDialogSurface';
export { ExtensionFederatedModuleHost } from './components/ExtensionFederatedModuleHost';
export { ExtensionRouteSurface } from './components/ExtensionRouteSurface';
export { ExtensionRouteView } from './components/ExtensionRouteView';
export { ExtensionSidePanelSurface, ExtensionSidePanelSurfaceContent, } from './components/ExtensionSidePanelSurface';
export { useExtensionSidePanelContributions } from './hooks/useExtensionSidePanelContributions';
export { agentLoopAuxiliarySurfacePayload, agentLoopInputKey, interactionSurfaceInput, resolveExtensionAgentLoopAuxiliaryContributions, } from './lib/extension-agent-loop-auxiliary-surfaces';
export { extensionAgentLoopEntryMatchesTarget, resolveExtensionAgentLoopContribution, resolveExtensionAgentLoopContributionEntries, } from './lib/extension-agent-loop-resolution';
export { surfaceLabel, surfacePayload, surfaceTarget, } from './lib/extension-agent-loop-surface-model';
export { refreshPreferencesAfterExtensionInvoke } from './lib/extension-broker-preferences';
export { resolveExtensionDialogContribution } from './lib/extension-dialog-resolution';
export { createExtensionMountContext, importFederatedModule, isFederatedModule, } from './lib/extension-federated-module';
export { createExtensionModuleUrl } from './lib/extension-module-url';
export { resolveExtensionRouteContribution } from './lib/extension-route-resolution';
export { resolveExtensionSidePanelContribution } from './lib/extension-side-panel-resolution';
