const CONTEXT_METER_HALF_DIVISOR = 2
const CONTEXT_METER_SIZE = 28
const CONTEXT_METER_STROKE_WIDTH = 2
const CONTEXT_METER_RADIUS =
  (CONTEXT_METER_SIZE - CONTEXT_METER_STROKE_WIDTH) / CONTEXT_METER_HALF_DIVISOR

export const CONTEXT_METER = {
  THRESHOLDS: {
    PERCENT_MAX: 100,
    WARNING_PERCENT: 70,
    ERROR_PERCENT: 90,
  },
  GEOMETRY: {
    SIZE: CONTEXT_METER_SIZE,
    STROKE_WIDTH: CONTEXT_METER_STROKE_WIDTH,
    RADIUS: CONTEXT_METER_RADIUS,
    CIRCUMFERENCE: CONTEXT_METER_HALF_DIVISOR * Math.PI * CONTEXT_METER_RADIUS,
    CENTER: CONTEXT_METER_SIZE / CONTEXT_METER_HALF_DIVISOR,
    VIEWBOX_SIZE: CONTEXT_METER_SIZE,
  },
}
