/**
 * Writes src/shared/usage-statistics/catalog.generated.ts: the public identifiers Usage
 * statistics may name. The statistics endpoint turns any provider, model, MCP server or skill
 * outside it into `custom`, so a private name never reaches PostHog even from a modified app.
 *
 * The sources are the ones the app maps against:
 * - Pi's built-in providers and their models, from `@earendil-works/pi-ai/providers/all`
 *   (src/main/adapters/pi/pi-usage-statistics.ts);
 * - OpenWaggle's curated MCP catalog, `MCP_CATALOG_SERVERS` (src/shared/constants/mcp.ts, as
 *   src/main/domain/usage-statistics/usage-statistics-mcp.ts uses it);
 * - the skills OpenWaggle ships, `USAGE_STATISTICS_BUILT_IN_SKILLS`
 *   (src/shared/usage-statistics/built-in-skills.ts).
 * Identifiers the wire contract cannot carry are left out; the app reports those as `custom`.
 *
 * Usage: `pnpm usage-statistics-catalog:generate` rewrites the file, and
 * `pnpm check:usage-statistics-catalog`, part of `pnpm check`, fails while it is out of date.
 */
import { execFileSync } from 'node:child_process'
import fs from 'node:fs/promises'
import path from 'node:path'
import { pathToFileURL } from 'node:url'
import { MCP_CATALOG_SERVERS } from '../src/shared/constants/mcp'
import { USAGE_STATISTICS_BUILT_IN_SKILLS } from '../src/shared/usage-statistics/built-in-skills'
import { usageStatisticsFieldError } from '../src/shared/usage-statistics/validation'

export const CATALOG_PATH = 'src/shared/usage-statistics/catalog.generated.ts'
const INDENT = '  '
const BIOME_LAUNCHER = 'node_modules/@biomejs/biome/bin/biome'
const FORMATTER_OUTPUT_LIMIT_BYTES = 16_777_216

export interface UsageStatisticsCatalogSource {
  readonly providerModels: ReadonlyMap<string, readonly string[]>
  readonly mcpServers: readonly string[]
  readonly skills: readonly string[]
}

function isPublishableIdentifier(value: string) {
  return usageStatisticsFieldError({ kind: 'identifier' }, value) === undefined
}

/** Unique, sorted identifiers that the wire contract can carry. */
export function catalogIdentifiers(values: Iterable<string>) {
  return [...new Set([...values].filter(isPublishableIdentifier))].sort()
}

function quoted(value: string) {
  return `'${value}'`
}

function stringList(values: readonly string[], indent: string) {
  if (values.length === 0) return '[]'
  return `[\n${values.map((value) => `${indent}${INDENT}${quoted(value)},`).join('\n')}\n${indent}]`
}

/** The generated module's text. Deterministic: the same catalogs always give the same bytes. */
export function renderUsageStatisticsCatalog(source: UsageStatisticsCatalogSource) {
  const providers = [...source.providerModels.keys()].filter(isPublishableIdentifier).sort()
  const entries = providers.map((provider) => {
    const models = catalogIdentifiers(source.providerModels.get(provider) ?? [])
    return `${INDENT}${quoted(provider)}: ${stringList(models, INDENT)},`
  })
  return [
    '// Generated by scripts/generate-usage-statistics-catalog.ts; do not edit. Regenerate with',
    '// `pnpm usage-statistics-catalog:generate`; `pnpm check:usage-statistics-catalog` fails when',
    "// this file no longer matches Pi's built-in catalog, the MCP catalog or the built-in skills.",
    '/**',
    ' * The public identifiers Usage statistics may name (docs/specs/usage-statistics-fields.md).',
    ' * The statistics endpoint reports any other provider, model, MCP server or skill as `custom`.',
    ' * Dependency-free and alias-free, because the endpoint bundles it.',
    ' */',
    '',
    "/** Pi's built-in providers, each with its built-in model ids. */",
    'export const USAGE_STATISTICS_CATALOG_PROVIDER_MODELS: Readonly<',
    '  Record<string, readonly string[]>',
    '> = {',
    ...entries,
    '}',
    '',
    "/** Server names in OpenWaggle's curated MCP catalog. */",
    `export const USAGE_STATISTICS_CATALOG_MCP_SERVERS: readonly string[] = ${stringList(catalogIdentifiers(source.mcpServers), '')}`,
    '',
    '/** Skills OpenWaggle ships. */',
    `export const USAGE_STATISTICS_CATALOG_SKILLS: readonly string[] = ${stringList(catalogIdentifiers(source.skills), '')}`,
    '',
  ].join('\n')
}

/** Reads the three catalogs from Pi, the MCP catalog and the built-in skill list. */
export async function loadUsageStatisticsCatalogSource(): Promise<UsageStatisticsCatalogSource> {
  // A dynamic import: Pi publishes this entry point for ESM only.
  const { getBuiltinModels, getBuiltinProviders } = await import(
    '@earendil-works/pi-ai/providers/all'
  )
  const providerModels = new Map(
    getBuiltinProviders().map((provider) => [
      provider,
      getBuiltinModels(provider).map((model) => model.id),
    ]),
  )
  return {
    providerModels,
    mcpServers: MCP_CATALOG_SERVERS.map((server) => server.name),
    skills: USAGE_STATISTICS_BUILT_IN_SKILLS,
  }
}

/**
 * The text as Biome formats it with the repository's settings, so `pnpm lint:fix` and
 * `pnpm format` never change the generated file and the check never fails after them.
 */
export function formatWithBiome(text: string, root: string) {
  return execFileSync(
    process.execPath,
    [path.join(root, BIOME_LAUNCHER), 'format', `--stdin-file-path=${CATALOG_PATH}`],
    { cwd: root, input: text, encoding: 'utf8', maxBuffer: FORMATTER_OUTPUT_LIMIT_BYTES },
  )
}

export interface CatalogGeneratorOptions {
  readonly root: string
  readonly check: boolean
  readonly log: (line: string) => void
}

/** Writes the catalog, or with `check` compares it; returns the process exit code. */
export async function runUsageStatisticsCatalogGenerator(options: CatalogGeneratorOptions) {
  const source = await loadUsageStatisticsCatalogSource()
  const expected = formatWithBiome(renderUsageStatisticsCatalog(source), options.root)
  const target = path.join(options.root, CATALOG_PATH)
  const current = await fs.readFile(target, 'utf8').catch(() => undefined)
  if (current === expected) {
    options.log(`${CATALOG_PATH} matches the catalogs.`)
    return 0
  }
  if (options.check) {
    options.log(`${CATALOG_PATH} is out of date. Run pnpm usage-statistics-catalog:generate.`)
    return 1
  }
  await fs.writeFile(target, expected)
  options.log(`Wrote ${CATALOG_PATH}.`)
  return 0
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  runUsageStatisticsCatalogGenerator({
    root: process.cwd(),
    check: process.argv.includes('--check'),
    log: (line) => console.log(line),
  })
    .then((code) => {
      process.exitCode = code
    })
    .catch((error: unknown) => {
      console.error(error instanceof Error ? error.message : error)
      process.exitCode = 1
    })
}
