const OPENWAGGLE_DOCS_ORIGIN = 'https://openwaggle.ai'
const PACKAGE_INSTALL_PATTERN =
  /<package-install packages="([^"]+)"><\/package-install>/gu

interface RenderPackageReadmeInput {
  readonly canonicalBody: string
  readonly description: string
  readonly docsUrl: string
  readonly packageName: string
}

function ensureTrailingSlash(url: string) {
  return url.endsWith('/') ? url : `${url}/`
}

export function packageInstallMarkdown(packages: string) {
  const packageList = packages.trim()
  return [
    '## Install',
    '',
    '### npm',
    '',
    '```bash',
    `npm install ${packageList}`,
    '```',
    '',
    '### pnpm',
    '',
    '```bash',
    `pnpm add ${packageList}`,
    '```',
    '',
    '### Yarn',
    '',
    '```bash',
    `yarn add ${packageList}`,
    '```',
    '',
    '### Bun',
    '',
    '```bash',
    `bun add ${packageList}`,
    '```',
  ].join('\n')
}

export function rewritePackageDocumentationLinks(markdown: string, docsUrl: string) {
  const versionedDocsUrl = ensureTrailingSlash(docsUrl)
  return markdown
    .replaceAll(/\]\(\/docs\/([^\s)#]+)\)/gu, (_match, pathValue: string) =>
      `](${OPENWAGGLE_DOCS_ORIGIN}/docs/${pathValue}/)`,
    )
    .replaceAll(/\]\(\.\/([^\s)#]+)\)/gu, (_match, pathValue: string) =>
      `](${versionedDocsUrl}${pathValue}/)`,
    )
}

export function renderPackageInstallElements(markdown: string) {
  return markdown.replaceAll(PACKAGE_INSTALL_PATTERN, (_match, packages: string) =>
    packageInstallMarkdown(packages),
  )
}

export function renderPackageReadme({
  canonicalBody,
  description,
  docsUrl,
  packageName,
}: RenderPackageReadmeInput) {
  const body = rewritePackageDocumentationLinks(
    renderPackageInstallElements(canonicalBody.trim()),
    docsUrl,
  )
  return [
    '<!-- Generated from the canonical OpenWaggle package documentation. -->',
    '<!-- Run `pnpm package-docs:update`; do not edit this file directly. -->',
    '',
    `# ${packageName}`,
    '',
    `[![npm version](https://img.shields.io/npm/v/${packageName}?color=f5a623)](https://www.npmjs.com/package/${packageName}) [![Node.js](https://img.shields.io/badge/Node.js-%3E%3D22.19-43853d)](${ensureTrailingSlash(docsUrl)}) [![License: MIT](https://img.shields.io/badge/License-MIT-blue.svg)](https://github.com/OpenWaggle/OpenWaggle/blob/main/LICENSE)`,
    '',
    description,
    '',
    `[Full documentation](${ensureTrailingSlash(docsUrl)}) · [OpenWaggle](https://openwaggle.ai/) · [Issues](https://github.com/OpenWaggle/OpenWaggle/issues)`,
    '',
    body,
    '',
    '## License',
    '',
    'MIT',
    '',
  ].join('\n')
}
