import type { SessionId } from '@shared/types/brand';
export declare function useSidebarController(): {
    draftBranch: import("../../sessions/state/session-store").DraftBranchState | null;
    draftSessionProjectPath: string | null;
    handleArchiveBranch: (sessionId: string, branch: import("../../../../../shared/types/session").SessionBranch) => void;
    handleArchiveProjectSessions: (path: string, projectSessions: readonly import("../../../../../shared/types/session").SessionSummary[]) => void;
    handleArchiveSession: (sessionId: SessionId) => void;
    handleCloneSession: (sessionId: SessionId) => void;
    handleDeleteSession: (sessionId: SessionId) => void;
    handleNewSession(): void;
    handleOpenProject: () => Promise<void>;
    handleOpenProjectInFinder: (path: string) => void;
    handleOpenSettings(): void;
    handleOpenSkills(): void;
    handleRemoveProject: (path: string) => void;
    handleRenameBranch: (sessionId: string, branch: import("../../../../../shared/types/session").SessionBranch, name: string) => void;
    handleRenameProject: (path: string, name: string) => void;
    handleSelectBranch: (sessionId: string, branch: import("../../../../../shared/types/session").SessionBranch) => void;
    handleSelectProjectPath: (path: string) => Promise<void>;
    handleSelectSession: (id: SessionId) => void;
    handleToggleBranches: (sessionId: SessionId, collapsed: boolean) => void;
    handleToggleProjectCollapsed(path: string): void;
    projectPath: string | null;
    activeBranchId: import("@shared/types/brand").SessionBranchId | null | undefined;
    activeSessionId: SessionId | null;
    activeView: import("../model").SidebarView;
    chat: import("../../chat/hooks/useChat").ChatReturn;
    collapsedProjectPaths: ReadonlySet<string>;
    displayProjectName: (path: string) => string;
    git: {
        workingPath: string | null;
        repositoryPath: string | null;
        status: import("../../../../../shared/types/git").GitStatusSummary | null;
        isLoading: boolean;
        error: string | null;
        branches: import("../../../../../shared/types/git").GitBranchListResult | null;
        isCommitting: boolean;
        isBranchActionRunning: boolean;
        refreshStatus: (workingPath: string | null) => Promise<void>;
        refreshBranches: (repositoryPath: string | null) => Promise<void>;
        commit: (workingPath: string, payload: import("../../../../../shared/types/git").GitCommitPayload) => Promise<import("../../../../../shared/types/git").GitCommitResult>;
        checkoutBranch: (workingPath: string, payload: import("../../../../../shared/types/git").GitBranchCheckoutPayload) => Promise<import("../../../../../shared/types/git").GitBranchMutationResult>;
        createBranch: (workingPath: string, payload: import("../../../../../shared/types/git").GitBranchCreatePayload) => Promise<import("../../../../../shared/types/git").GitBranchMutationResult>;
    };
    isFullscreen: boolean;
    matchingActiveSessionTree: import("../../../../../shared/types/session").SessionTree | null;
    matchingActiveWorkspace: import("../../../../../shared/types/session").SessionWorkspace | null;
    navigate: import("@tanstack/router-core").UseNavigateResult<string>;
    preferences: {
        removeProjectReferences: (path: string) => Promise<void>;
        selectedModel: import("@shared/types/brand").SupportedModelId;
        setProjectDisplayName: (path: string, name: string) => Promise<void>;
    };
    project: {
        projectPath: string | null;
        selectFolder: () => Promise<string | null>;
        setProjectPath: (path: string | null) => Promise<void>;
    };
    sessionGroups: import("../lib/sidebar-project-groups").SidebarProjectGroups;
    sessions: import("../../sessions/hooks/useSessions").SessionsReturn;
    setCollapsedProjectPaths: import("node_modules/@types/react").Dispatch<import("node_modules/@types/react").SetStateAction<ReadonlySet<string>>>;
    setSortMenuOpen: import("node_modules/@types/react").Dispatch<import("node_modules/@types/react").SetStateAction<boolean>>;
    setSortMode: import("node_modules/@types/react").Dispatch<import("node_modules/@types/react").SetStateAction<import("../lib/sidebar-project-groups").SidebarSessionSortMode>>;
    showToast: (message: string, variant?: import("../../../shell/ui-store").ToastData["variant"]) => void;
    sidebarOpen: boolean;
    sortMenuOpen: boolean;
    sortMode: import("../lib/sidebar-project-groups").SidebarSessionSortMode;
};
