import type { CSSProperties } from 'react';
export declare const RESIZE_MOVE_THRESHOLD_PX = 2;
export declare const RESIZE_RAIL_HALF_WIDTH_PX = 8;
export declare const RESIZE_BODY_CLASS = "right-sidebar-resizing";
export declare const SHEET_MAX_WIDTH_PX = 820;
export declare const SHEET_VIEWPORT_WIDTH = "88vw";
export declare function clampWidth(width: number, minWidth: number, maxWidth: number): number;
export declare function readStoredWidth(storageKey: string, fallbackWidth: number): number;
export declare function persistWidth(storageKey: string, width: number): void;
export declare function pixelValue(value: number): string;
export declare function sidebarWidthValue(width: number, mainMinWidth: number): string;
export declare function sidebarShellStyle(open: boolean, width: number, mainMinWidth: number): CSSProperties;
export declare function sidebarPanelStyle(): CSSProperties;
export declare function resizeRailRightValue(open: boolean, width: number, mainMinWidth: number): string;
export declare function resizeRailStyle(open: boolean, width: number, mainMinWidth: number): CSSProperties;
export declare function clampedVisibleWidth(width: number, minWidth: number, maxWidth: number, rootWidth: number, mainMinWidth: number): number;
