export const PRELOAD_MCP_METHODS = [
  'getMcpSettings',
  'setMcpScopeState',
  'setMcpServerEnabled',
  'setMcpProjectServerEnabled',
  'setMcpServerTrust',
  'writeMcpSourceConfig',
  'removeMcpServer',
  'authorizeMcpServer',
  'logoutMcpServer',
  'addMcpServer',
  'previewMcpImports',
  'applyMcpImports',
  'doctorMcp',
  'listMcpSecrets',
  'setMcpSecret',
  'removeMcpSecret',
  'listMcpCapabilities',
  'getMcpPrompt',
  'readMcpResource',
  'reviewMcpRemoteSkill',
  'operateMcpTask',
  'callMcpAppTool',
  'setMcpEventSubscription',
  'listMcpEvents',
  'listMcpEventSubscriptions',
] as const
