/**
 * Every method the preload bridge exposes.
 *
 * Kept beside the test rather than inside it, like PRELOAD_MCP_METHODS, so the contract list can
 * grow without pushing the test file past its line budget.
 */
import type { OpenWaggleApi } from '@shared/types/openwaggle-api'
import { PRELOAD_MCP_METHODS } from './preload-mcp-methods'

export const PRELOAD_API_METHODS: readonly (keyof OpenWaggleApi)[] = [
  // Agent
  'sendMessage',
  'cancelAgent',
  'steerAgent',
  'respondAgentInteraction',
  'onAgentEvent',
  'getAgentPhase',
  'getBackgroundRun',
  'listActiveRuns',
  'getContextUsage',
  'compactSession',
  'onRunCompleted',
  'onAgentPhase',
  'onWorktreeLaunch',
  // Settings
  'getSettings',
  'updateSettings',
  'setEnabledModels',
  'getPiTreeFilterMode',
  'setPiTreeFilterMode',
  'getPiBranchSummarySkipPrompt',
  'testApiKey',
  ...PRELOAD_MCP_METHODS,
  'listExtensionPackages',
  'listExtensionContributions',
  'proposeExtensionPackageWrite',
  'applyExtensionPackageWrite',
  'proposeExtensionPackageRemove',
  'applyExtensionPackageRemove',
  'invokeExtension',
  'registerExtensionFrame',
  'unregisterExtensionFrame',
  'setExtensionTrusted',
  'setExtensionEnabled',
  'setExtensionProjectDisabled',
  'acceptExtensionUpdate',
  'approveExtensionBuild',
  'reloadExtension',
  'discoverDocs',
  'resolveDocsTopic',
  'setProviderApiKey',
  // Providers
  'getProviderModels',
  // Project
  'selectProjectFolder',
  'getProjectPreferences',
  'setProjectPreferences',
  'listAuthorizationGrants',
  'grantAuthorization',
  'revokeAuthorization',
  'searchWorkspaceFiles',
  'searchWorkspaceContent',
  'cancelWorkspaceContentSearch',
  'readWorkspaceFile',
  'writeWorkspaceFile',
  'openWorkspaceFileExternal',
  'listSessions',
  'listSessionDetails',
  'getSessionDetail',
  'listTurnCheckpoints',
  'getTurnDiff',
  'listPinnedSessions',
  'pinSession',
  'unpinSession',
  'movePinnedSession',
  'createSession',
  'forkSessionToNew',
  'cloneSessionToNew',
  'dismissInterruptedSessionRun',
  'deleteSession',
  'archiveSession',
  'unarchiveSession',
  'listArchivedSessions',
  'updateSessionTitle',
  'setSessionWorktreePlan',
  'setSessionAuthorizationMode',
  'listArchivedSessionBranches',
  'getSessionTree',
  'getSessionWorkspace',
  'navigateSessionTree',
  'renameSessionBranch',
  'archiveSessionBranch',
  'restoreSessionBranch',
  'updateSessionTreeUiState',
  'onGitWorkingTreeChanged',
  'onSessionTitleUpdated',
  // Terminal
  'createTerminal',
  'closeTerminal',
  'resizeTerminal',
  'writeTerminal',
  'onTerminalData',
  // Window
  'onFullscreenChanged',
  // Git
  'getGitStatus',
  'commitGit',
  'getGitDiff',
  'getGitBranchDiff',
  'stageAllGitChanges',
  'revertAllGitChanges',
  'listGitBranches',
  'checkoutGitBranch',
  'createGitBranch',
  'listGitWorktrees',
  'createGitWorktree',
  'removeGitWorktree',
  'getLocalVcsStatus',
  'getRemoteVcsStatus',
  'runStackedGitAction',
  'listChangeRequests',
  'checkoutChangeRequest',
  // Attachments
  'prepareAttachments',
  'prepareAttachmentFromText',
  'onPrepareAttachmentFromTextProgress',
  // Voice
  'transcribeVoiceLocal',
  // Standards & Skills
  'getStandardsStatus',
  'getEffectiveAgents',
  'listSkills',
  'setSkillEnabled',
  'getSkillPreview',
  // Shell / App
  'copyToClipboard',
  'openLogsDir',
  'getLogsPath',
  'openPath',
  // Dialog
  'showConfirm',
  // Waggle
  'sendWaggleMessage',
  'cancelWaggle',
  'onWaggleEvent',
  'onWaggleTurnEvent',
  // Auth
  'startOAuth',
  'submitAuthCode',
  'cancelOAuth',
  'disconnectAuth',
  'getAuthAccountInfo',
  'onOAuthStatus',
  // Waggle presets
  'listWagglePresets',
  'saveWagglePreset',
  'deleteWagglePreset',
  // Feedback
  'checkGhCli',
  'collectDiagnostics',
  'getRecentLogs',
  'submitFeedback',
  'generateFeedbackMarkdown',
  'openExternal',
  // Composer
  'suggestFiles',
  // Auto-updater
  'checkForUpdates',
  'checkSessionWorktree',
  'installUpdate',
  'getUpdateStatus',
  'getAppVersion',
  'onUpdateStatus',
]
