/** Preserve a final native failure without reusing LASTEXITCODE from an earlier statement. */
export function powerShellFailureExitCode(statementDiscovery: readonly string[]) {
  return [
    ...statementDiscovery,
    '$__ow_exit = 1',
    'if ($__ow_statement -is [System.Management.Automation.Language.PipelineAst]) {',
    '  $__ow_last = $__ow_statement.PipelineElements[-1]',
    '  if ($__ow_last -is [System.Management.Automation.Language.CommandAst]) {',
    '    $__ow_name = $__ow_last.GetCommandName()',
    '    if (!$__ow_name -and $__ow_last.InvocationOperator -eq [System.Management.Automation.Language.TokenKind]::Ampersand) {',
    '      $__ow_first = $__ow_last.CommandElements[0]',
    '      if ($__ow_first -is [System.Management.Automation.Language.VariableExpressionAst]) {',
    '        $__ow_name = Get-Variable -Name $__ow_first.VariablePath.UserPath -ValueOnly -ErrorAction SilentlyContinue',
    '      }',
    '      if ($__ow_first -is [System.Management.Automation.Language.IndexExpressionAst] -and $__ow_first.Target -is [System.Management.Automation.Language.VariableExpressionAst]) {',
    '        $__ow_target = Get-Variable -Name $__ow_first.Target.VariablePath.UserPath -ErrorAction SilentlyContinue',
    '        $__ow_index = $null',
    '        if ($__ow_first.Index -is [System.Management.Automation.Language.ConstantExpressionAst]) { $__ow_index = $__ow_first.Index.Value }',
    '        elseif ($__ow_first.Index -is [System.Management.Automation.Language.VariableExpressionAst]) {',
    '          $__ow_indexVariable = Get-Variable -Name $__ow_first.Index.VariablePath.UserPath -ErrorAction SilentlyContinue',
    '          if ($__ow_indexVariable) { $__ow_index = $__ow_indexVariable.Value }',
    '        }',
    '        if ($__ow_target -and $null -ne $__ow_index) {',
    '          try { $__ow_name = $__ow_target.Value[$__ow_index] } catch { $__ow_name = $null }',
    '        }',
    '      }',
    '    }',
    '    if ($__ow_name) {',
    '      $__ow_info = Get-Command -Name $__ow_name -ErrorAction SilentlyContinue | Select-Object -First 1',
    '      while ($__ow_info -is [System.Management.Automation.AliasInfo]) { $__ow_info = $__ow_info.ResolvedCommand }',
    '      if ($__ow_info -and $__ow_info.CommandType -eq [System.Management.Automation.CommandTypes]::Application -and $__ow_nativeExit -ne 0) { $__ow_exit = $__ow_nativeExit }',
    '    }',
    '  }',
    '}',
  ].join('\n')
}
