/** Preserve a final native failure without reusing LASTEXITCODE from an earlier statement. */
export function powerShellFailureExitCode(statementDiscovery: readonly string[]) {
  return [
    ...statementDiscovery,
    // Resolve only inert AST shapes. Evaluating the command expression again could rerun user code.
    'function __ow_resolve_command_expression($ast) {',
    '  if ($ast -is [System.Management.Automation.Language.VariableExpressionAst]) {',
    '    if ($ast.VariablePath.IsDriveQualified) {',
    '      if ($ast.VariablePath.DriveName -ine "Env") { return $null }',
    '      $__ow_envName = $ast.VariablePath.UserPath.Substring($ast.VariablePath.DriveName.Length + 1)',
    '      return ,[System.Environment]::GetEnvironmentVariable($__ow_envName)',
    '    }',
    '    $__ow_variable = Get-Variable -Name $ast.VariablePath.UserPath -ErrorAction SilentlyContinue',
    '    if ($__ow_variable) { return ,$__ow_variable.Value }',
    '    return $null',
    '  }',
    '  if ($ast -is [System.Management.Automation.Language.ConstantExpressionAst]) { return ,$ast.Value }',
    '  if ($ast -is [System.Management.Automation.Language.ExpandableStringExpressionAst]) {',
    '    $__ow_source = $ast.Extent.Text',
    '    if ($__ow_source.Length -lt 2 -or $__ow_source[0] -ne [char]34 -or $__ow_source[-1] -ne [char]34) { return $null }',
    '    $__ow_cursor = $ast.Extent.StartOffset + 1',
    '    $__ow_result = ""',
    '    foreach ($__ow_nested in $ast.NestedExpressions) {',
    '      if ($__ow_nested.Extent.StartOffset -lt $__ow_cursor) { return $null }',
    '      $__ow_literal = $__ow_source.Substring($__ow_cursor - $ast.Extent.StartOffset, $__ow_nested.Extent.StartOffset - $__ow_cursor)',
    '      if ($__ow_literal.IndexOf([char]96) -ge 0) { return $null }',
    '      $__ow_value = __ow_resolve_command_expression $__ow_nested',
    '      if ($__ow_value -isnot [string]) { return $null }',
    '      $__ow_result += $__ow_literal + $__ow_value',
    '      $__ow_cursor = $__ow_nested.Extent.EndOffset',
    '    }',
    '    $__ow_tail = $__ow_source.Substring($__ow_cursor - $ast.Extent.StartOffset, $ast.Extent.EndOffset - 1 - $__ow_cursor)',
    '    if ($__ow_tail.IndexOf([char]96) -ge 0) { return $null }',
    '    return ,($__ow_result + $__ow_tail)',
    '  }',
    '  if ($ast -is [System.Management.Automation.Language.ParenExpressionAst] -or',
    '      $ast -is [System.Management.Automation.Language.SubExpressionAst]) {',
    '    if ($ast -is [System.Management.Automation.Language.ParenExpressionAst]) {',
    '      $__ow_pipeline = $ast.Pipeline',
    '    } else {',
    '      if ($ast.SubExpression.Statements.Count -ne 1) { return $null }',
    '      $__ow_pipeline = $ast.SubExpression.Statements[0]',
    '    }',
    '    if ($__ow_pipeline -isnot [System.Management.Automation.Language.PipelineAst] -or',
    '        $__ow_pipeline.PipelineElements.Count -ne 1) { return $null }',
    '    $__ow_element = $__ow_pipeline.PipelineElements[0]',
    '    if ($__ow_element -isnot [System.Management.Automation.Language.CommandExpressionAst]) { return $null }',
    '    $__ow_inner = __ow_resolve_command_expression $__ow_element.Expression',
    '    return ,$__ow_inner',
    '  }',
    '  if ($ast -is [System.Management.Automation.Language.IndexExpressionAst]) {',
    '    $__ow_target = __ow_resolve_command_expression $ast.Target',
    '    $__ow_index = __ow_resolve_command_expression $ast.Index',
    '    if ($null -ne $__ow_target -and $null -ne $__ow_index) {',
    '      try { return ,$__ow_target[$__ow_index] } catch { return $null }',
    '    }',
    '    return $null',
    '  }',
    '  if ($ast -is [System.Management.Automation.Language.MemberExpressionAst] -and',
    '      $ast -isnot [System.Management.Automation.Language.InvokeMemberExpressionAst] -and -not $ast.Static) {',
    '    $__ow_target = __ow_resolve_command_expression $ast.Expression',
    '    $__ow_member = __ow_resolve_command_expression $ast.Member',
    '    if ($null -eq $__ow_target -or $__ow_member -isnot [string]) { return $null }',
    '    if ($__ow_target -is [System.Collections.IDictionary]) {',
    '      if ($__ow_target.Contains($__ow_member)) { return ,$__ow_target[$__ow_member] }',
    '      return $null',
    '    }',
    '    $__ow_property = $__ow_target.PSObject.Properties[$__ow_member]',
    '    if ($__ow_property -is [System.Management.Automation.PSNoteProperty]) { return ,$__ow_property.Value }',
    '  }',
    '  return $null',
    '}',
    '$__ow_exit = 1',
    'if ($__ow_statement -is [System.Management.Automation.Language.PipelineAst]) {',
    '  $__ow_last = $__ow_statement.PipelineElements[-1]',
    '  if ($__ow_last -is [System.Management.Automation.Language.CommandAst]) {',
    '    $__ow_name = $__ow_last.GetCommandName()',
    '    if (!$__ow_name -and $__ow_last.InvocationOperator -eq [System.Management.Automation.Language.TokenKind]::Ampersand) {',
    '      $__ow_name = __ow_resolve_command_expression $__ow_last.CommandElements[0]',
    '    }',
    '    if ($__ow_name) {',
    '      $__ow_info = Get-Command -Name $__ow_name -ErrorAction SilentlyContinue | Select-Object -First 1',
    '      while ($__ow_info -is [System.Management.Automation.AliasInfo]) { $__ow_info = $__ow_info.ResolvedCommand }',
    '      if ($__ow_info -and $__ow_info.CommandType -eq [System.Management.Automation.CommandTypes]::Application -and $__ow_nativeExit -ne 0) { $__ow_exit = $__ow_nativeExit }',
    '    }',
    '  }',
    '}',
  ].join('\n')
}
