// Keep the capture EXIT trap private while sourced scripts inspect or replace their own cleanup.
export const bashZshUserTraps = [
  '__ow_print_user_exit_trap() {',
  'if [ "$__ow_user_exit_trap_set" -eq 1 ]; then builtin printf \'trap -- %q EXIT\\n\' "$__ow_user_exit_trap"; fi',
  '}',
  '__ow_print_user_traps() {',
  'if [ "$#" -eq 0 ]; then',
  '(builtin trap - EXIT; builtin trap)',
  '__ow_print_user_exit_trap',
  'return',
  'fi',
  'local __ow_signal',
  'for __ow_signal in "$@"; do',
  'case "$__ow_signal" in',
  'EXIT|0) __ow_print_user_exit_trap ;;',
  '*) builtin trap -p "$__ow_signal" ;;',
  'esac',
  'done',
  '}',
  'trap() {',
  'if [ "$#" -eq 0 ]; then __ow_print_user_traps; return; fi',
  'if [ "$1" = \'-p\' ]; then shift; __ow_print_user_traps "$@"; return; fi',
  'if [ "$1" = \'-l\' ]; then builtin trap "$@"; return; fi',
  'if [ "$1" = \'--\' ]; then shift; fi',
  'if [ "$#" -eq 0 ]; then __ow_print_user_traps; return; fi',
  'if [ "$#" -eq 1 ]; then case "$1" in EXIT|0) __ow_user_exit_trap=\'\'; __ow_user_exit_trap_set=0; return ;; *) builtin trap "$@"; return ;; esac; fi',
  'if [ "$#" -lt 2 ]; then builtin trap "$@"; return; fi',
  'local __ow_handler="$1" __ow_signal',
  'shift',
  'for __ow_signal in "$@"; do',
  'case "$__ow_signal" in',
  'EXIT|0) if [ "$__ow_handler" = \'-\' ]; then __ow_user_exit_trap=\'\'; __ow_user_exit_trap_set=0; else __ow_user_exit_trap="$__ow_handler"; __ow_user_exit_trap_set=1; fi ;;',
  '*) builtin trap "$__ow_handler" "$__ow_signal" ;;',
  'esac',
  'done',
  '}',
].join('\n')
