export type {
  ExtensionCapabilityAuditEntry,
  ExtensionHostContextResult,
  ExtensionInvokeError,
  ExtensionInvokeFailure,
  ExtensionInvokeFailureCode,
  ExtensionInvokeInput,
  ExtensionInvokeOutcome,
  ExtensionInvokeResult,
  ExtensionInvokeScope,
  ExtensionInvokeSuccess,
  ExtensionInvokeSuccessValue,
  ExtensionStorageDeletePayload,
  ExtensionStorageDeleteResult,
  ExtensionStorageGetPayload,
  ExtensionStorageGetResult,
  ExtensionStorageKind,
  ExtensionStorageListPayload,
  ExtensionStorageListResult,
  ExtensionStorageScope,
  ExtensionStorageScopeSelector,
  ExtensionStorageSetPayload,
  ExtensionStorageSetResult,
} from '@shared/schemas/extension-broker'
