import type { PreparedAttachment } from '@shared/types/agent';
import type { LexicalEditor } from 'lexical';
import type { ComposerGet, ComposerSet, MenuKind } from './composer-store-types';
export declare function createComposerStoreState(set: ComposerSet, get: ComposerGet): {
    reset: () => void;
    lexicalEditor: null;
    setLexicalEditor(editor: LexicalEditor | null): void;
    setSlashHighlightIndex(index: number): void;
    setDismissedSlashToken(token: string | null): void;
    openMenu(menu: MenuKind): void;
    setActiveDraftContextKey(contextKey: string | null): void;
    switchScopedDraftContext(contextKey: string, fallbackDraft?: import("./composer-store-types").ComposerScopedDraft, currentDraftOverride?: import("./composer-store-types").ComposerScopedDraft): {
        input: string;
        attachments: import("@shared/types/agent").AttachmentRecord[];
    };
    saveScopedDraft(contextKey: string, draft: import("./composer-store-types").ComposerScopedDraft): void;
    getScopedDraft(contextKey: string): import("./composer-store-types").ComposerScopedDraft;
    clearScopedDraft(contextKey: string): void;
    clearScopedDraftsForSession(sessionId: string): void;
    clearScopedDraftsForBranch(sessionId: string, branchId: string): void;
    addAttachments(files: PreparedAttachment[]): void;
    replaceAttachments(files: readonly PreparedAttachment[]): void;
    removeAttachment(id: string): void;
    setAttachmentError(error: string | null): void;
    pushHistory(text: string): void;
    historyUp(currentInput: string): string | null;
    historyDown(): string | null;
    setInput(value: string): void;
    setCursorIndex(index: number): void;
    input: string;
    cursorIndex: number;
    promptHistory: readonly string[];
    historyIndex: number;
    draftInput: string;
    attachments: PreparedAttachment[];
    attachmentError: string | null;
    activeDraftContextKey: string | null;
    scopedDrafts: Readonly<Record<string, import("./composer-store-types").ComposerScopedDraft>>;
    thinkingMenuOpen: boolean;
    executionMenuOpen: boolean;
    branchMenuOpen: boolean;
    slashHighlightIndex: number;
    dismissedSlashToken: string | null;
};
